var DefaultSearchNodes	= {
	matchTaskSubmitQuota	: '<SimpFilter><Group><ColNode Col="MATCH_PRIORITY" Op="in" Dt="n"></ColNode><ColNode Col="BTY_MASK" Op="in" Dt="n"></ColNode><ColNode Col="QRY_TYPE" Op="in" Dt="n"></ColNode><ColNode Col="QRY_STATUS" Op="in" Dt="s"></ColNode></Group></SimpFilter>',
	
	tpCardDataFilter_add	: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>TP_CARD_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="BTY_MASK" Op="in" Dt="n"></ColNode><ColNode Col="DBID" Op="in" Dt="s"></ColNode></Group></SimpFilter></Where></TextFilter>',
	tpCardDataFilter		: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>TP_CARD_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="BTY_MASK" Op="in" Dt="n"></ColNode><ColNode Col="DBID" Op="in" Dt="s"></ColNode><ColNode Col="CREATE_USER" Op="eq" Dt="s"></ColNode><ColNode Col="CREATE_UNIT_CODE" Op="in" Dt="s"></ColNode></Group></SimpFilter></Where></TextFilter>',
	
	lpCaseDataFilter_add	: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>LP_CASE_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="DBID" Op="in" Dt="s"></ColNode></Group></SimpFilter></Where></TextFilter>',
	lpCaseDataFilter		: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>LP_CASE_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="DBID" Op="in" Dt="s"></ColNode><ColNode Col="CREATE_USER" Op="eq" Dt="s"></ColNode><ColNode Col="CREATE_UNIT_CODE" Op="in" Dt="s"></ColNode></Group></SimpFilter></Where></TextFilter>',
	
	lpCardDataFilter_add	: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>LP_CARD_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="BTY" Op="in" Dt="n"></ColNode><ColNode Col="DBID" Op="in" Dt="s"></ColNode></Group></SimpFilter></Where></TextFilter>',
	lpCardDataFilter	    : '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>LP_CARD_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="BTY" Op="in" Dt="n"></ColNode><ColNode Col="DBID" Op="in" Dt="s"></ColNode><ColNode Col="CREATE_USER" Op="eq" Dt="s"></ColNode></Group></SimpFilter></Where></TextFilter>',
	
	matchDataFilter_add		: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>MATCH_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="MATCH_PRIORITY" Op="in" Dt="n"></ColNode><ColNode Col="QRY_TYPE" Op="in" Dt="n"></ColNode><ColNode Col="DBID" Op="in" Dt="s"></ColNode><ColNode Col="BTY_MASK" Op="in" Dt="n"></ColNode></Group></SimpFilter></Where></TextFilter>',
	matchDataFilter			: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>MATCH_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="MATCH_PRIORITY" Op="in" Dt="n"></ColNode><ColNode Col="QRY_TYPE" Op="in" Dt="n"></ColNode><ColNode Col="DBID" Op="in" Dt="s"></ColNode><ColNode Col="BTY_MASK" Op="in" Dt="n"></ColNode><ColNode Col="SUBMIT_USER" Op="eq" Dt="s"></ColNode><ColNode Col="SUBMIT_UNIT_CODE" Op="in" Dt="s"></ColNode></Group></SimpFilter></Where></TextFilter>',
	
	userDataFilter			: '<?xml version="1.0"' +
	' encoding="UTF-8"?><TextFilter><Projection><Pi>*</Pi></Projection><From><Table>USER_IDENTITY_INFO_VIEW</Table></From><OrderBy><Oi Order="DESC">URID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="CLIENT_MACS" Op="eq" Dt="s"><Arg Dt="s" Lt="const"></Arg></ColNode><ColNode Col="CLIENT_IPS" Op="eq" Dt="s"><Arg Dt="s" Lt="const"></Arg></ColNode><ColNode Col="USER_UNIT_CODE" Op="in" Dt="s"><Arg Dt="s" Lt="const"></Arg></ColNode><ColNode Col="USER_ACCESS_WEEK_DAY" Op="in" Dt="s"><Arg Dt="s" Lt="const"></Arg></ColNode><ColNode Col="USER_ACCESS_DATE" Op="eq" Dt="s"><Arg Dt="s" Lt="const"></Arg></ColNode><ColNode Col="USER_ACCESS_TIME" Op="eq" Dt="s"><Arg Dt="s" Lt="const"></Arg></ColNode></Group></SimpFilter></Where></TextFilter>',
	dbDataFilter_add		: '<?xml version="1.0"' +
	' encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>DB_CATLOG_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">DBID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="DBID" Op="in" Dt="s"></ColNode><ColNode Col="DB_PURPOSE" Op="in" Dt="s"></ColNode><ColNode Col="DB_TYPE" Op="in" Dt="n"></ColNode></Group></SimpFilter></Where></TextFilter>',
	dbDataFilter			: '<?xml version="1.0"' +
	' encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>DB_CATLOG_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">DBID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="DBID" Op="in" Dt="s"></ColNode><ColNode Col="DB_PURPOSE" Op="in" Dt="s"></ColNode><ColNode Col="DB_TYPE" Op="in" Dt="n"></ColNode><ColNode Col="CREATE_USER" Op="eq" Dt="s"></ColNode><ColNode Col="CREATE_UNIT_CODE" Op="in" Dt="s"></ColNode></Group></SimpFilter></Where></TextFilter>',
	
	matchPartitionDataFilter_add: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>MATCH_PART_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="DBID" Op="in" Dt="s"><Arg Lt="const" Dt="s"></Arg></ColNode><ColNode Col="PART_TYPE" Op="in" Dt="n"><Arg Lt="const" Dt="n"></Arg></ColNode><ColNode Col="BTY_MASK" Op="in" Dt="n"><Arg Lt="const" Dt="n"></Arg></ColNode><ColNode Col="PRINT_TYPE" Op="in" Dt="n"><Arg Lt="const" Dt="n"></Arg></ColNode></Group></SimpFilter></Where></TextFilter>',
	matchPartitionDataFilter: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>MATCH_PART_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="DBID" Op="in" Dt="s"><Arg Lt="const" Dt="s"></Arg></ColNode><ColNode Col="PART_TYPE" Op="in" Dt="n"><Arg Lt="const" Dt="n"></Arg></ColNode><ColNode Col="BTY_MASK" Op="in" Dt="n"><Arg Lt="const" Dt="n"></Arg></ColNode><ColNode Col="PRINT_TYPE" Op="in" Dt="n"><Arg Lt="const" Dt="n"></Arg></ColNode><ColNode Col="CREATE_USER" Op="eq" Dt="s"><Arg Lt="const" Dt="s"></Arg></ColNode><ColNode Col="UNIT_CODE" Op="in" Dt="s"><Arg Lt="const" Dt="s"></Arg></ColNode></Group></SimpFilter></Where></TextFilter>',
	
	LTLHitLogDataFilter_add	: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>LTL_HITLOG_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="QRY_TYPE" Op="in" Dt="n"></ColNode><ColNode Col="BTY_MASK" Op="in" Dt="n"></ColNode><ColNode Col="MATCH_PRIORITY" Op="in" Dt="n"></ColNode></Group></SimpFilter></Where></TextFilter>',
	LTLHitLogDataFilter		: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>LTL_HITLOG_FOR_DATAFILTER_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="QRY_TYPE" Op="in" Dt="n"></ColNode><ColNode Col="BTY_MASK" Op="in" Dt="n"></ColNode><ColNode Col="MATCH_PRIORITY" Op="in" Dt="n"></ColNode><ColNode Col="CREATE_USER" Op="eq" Dt="s"></ColNode><ColNode Col="CREATE_UNIT_CODE" Op="in" Dt="s"></ColNode></Group></SimpFilter></Where></TextFilter>',
	
	tpFeedBack				: '<?xml version="1.0" encoding="UTF-8"?><TextFilter><Projection>*</Projection><From><Table>MP_ENROLL_FEEDBACK_VIEW</Table></From><OrderBy><Oi Order="DESC">ID</Oi></OrderBy><Where><SimpFilter><Group><ColNode Col="CARD_NUM" Op="like" Dt="s"></ColNode><ColNode Col="NAME" Op="like" Dt="s"></ColNode><ColNode Col="PERSON_NUM" Op="like" Dt="s"></ColNode></Group></SimpFilter></Where></TextFilter>'
};
