var properties = '';

properties += '<div class="select_properties">                                                                                  ';
properties += '<div class="select-header">                                                                                      ';
properties += '      <span class="select-current">样式属性选择</span>                                                           ';
properties += '      <span class="select-panel-close">                                                                          ';
properties += '            <a class="fa fa-close" href="javascript:void(0)" onclick="draw.tooltip.setPosition(undefined)"></a>             ';
properties += '      </span>                                                                                                    ';
properties += '</div>                                                                                                           ';
properties += '<div class="properties_title">外边框线颜色</div>                                                                 ';
properties += '<div class="properties_cont">                                                                                    ';
properties += '    <div class="stroke">                                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,0,255" class="a1"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="255,0,0" class="a2"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="255,255,0" class="a3 on"></a>                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,128,0" class="a4"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="128,0,128" class="a5"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,0,0" class="a6"></a>                                                                             ';
properties += '    </div>                                                                                                       ';
properties += '</div>                                                                                                           ';
properties += '<div class="properties_title">线粗细</div>                                                                 ';
properties += '<div class="properties_cont">                                                                                    ';
properties += '    <div class="width">                                                                                           ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="1" class="a1">1PX</a>                                                                       ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="2" class="a1 on">2PX</a>                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="3" class="a1">3PX</a>                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="4" class="a1">4PX</a>                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="6" class="a1">6PX</a>                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="8" class="a1">8PX</a>                                                                          ';
properties += '    </div>                                                                                                       ';
properties += '</div>                                                                                                           ';
properties += '<div class="properties_title">内部填充颜色</div>                                                                 ';
properties += '<div class="properties_cont">                                                                                    ';
properties += '    <div class="fill">                                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,0,255" class="a1"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="255,0,0" class="a2"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="255,255,0" class="a3"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,128,0" class="a4 on"></a>                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="128,0,128" class="a5"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,0,0" class="a6"></a>                                                                             ';
properties += '    </div>                                                                                                       ';
properties += '</div>                                                                                                           ';
properties += '<div class="properties_title">内部填充颜色透明度</div>                                                           ';
properties += '<div class="properties_cont">                                                                                    ';
properties += '     <div class="alpha">                                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="1" class="a1">10%</a>                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0.8" class="a1">25%</a>                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0.6" class="a1">50%</a>                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0.3" class="a1">75%</a>                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0.1" class="a1">85%</a>                                                                          ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0" class="a1 on">100%</a>                                                                      ';
properties += '    </div>                                                                                                       ';
properties += '</div>                                                                                                           ';
properties += '<div class="properties_title">图标样式</div>                                                                     ';
properties += '<div class="properties_cont">                                                                                    ';
properties += '     <div class="image">                                                                                        ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local1" class="a1 on"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local2" class="a2"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local3" class="a3"></a>                                                                            ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local4" class="a4"></a>                                                                            ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local5" class="a5"></a>                                                                            ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local6" class="a6"></a>                                                                            ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local7" class="a7"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local8" class="a8"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local9" class="a9"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local10" class="a10"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local11" class="a11"></a>                                                                             ';
properties += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local12" class="a12"></a>                                                                             ';
properties += '    </div>                                                                                                       ';
properties += '</div>                                                                                                           ';
properties += '<div class="properties_btn">                                                                                     ';
properties += '     <a href="javascript:void(0)" onclick="draw.save()">保存</a><a href="javascript:void(0)" onclick="draw.delSelect()">删除</a> ';
properties += '</div>                                                                                                           ';
properties += '</div>                                                                                                           ';

//=============================
var propertiesPolygon = '';

propertiesPolygon += '<div class="select_properties">                                                                                  ';
propertiesPolygon += '<div class="select-header">                                                                                      ';
propertiesPolygon += '      <span class="select-current">样式属性选择</span>                                                           ';
propertiesPolygon += '      <span class="select-panel-close">                                                                          ';
propertiesPolygon += '            <a class="fa fa-close" href="javascript:void(0)" onclick="draw.tooltip.setPosition(undefined)"></a>             ';
propertiesPolygon += '      </span>                                                                                                    ';
propertiesPolygon += '</div>                                                                                                           ';
propertiesPolygon += '<div class="properties_title">外边框线颜色</div>                                                                 ';
propertiesPolygon += '<div class="properties_cont">                                                                                    ';
propertiesPolygon += '    <div class="stroke">                                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,0,255" class="a1"></a>                                                                             ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="255,0,0" class="a2"></a>                                                                             ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="255,255,0" class="a3 on"></a>                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,128,0" class="a4"></a>                                                                             ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="128,0,128" class="a5"></a>                                                                             ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,0,0" class="a6"></a>                                                                             ';
propertiesPolygon += '    </div>                                                                                                       ';
propertiesPolygon += '</div>                                                                                                           ';
propertiesPolygon += '<div class="properties_title">线粗细</div>                                                                 ';
propertiesPolygon += '<div class="properties_cont">                                                                                    ';
propertiesPolygon += '    <div class="width">                                                                                           ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="1" class="a1">1PX</a>                                                                       ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="2" class="a1 on">2PX</a>                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="3" class="a1">3PX</a>                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="4" class="a1">4PX</a>                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="6" class="a1">6PX</a>                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="8" class="a1">8PX</a>                                                                          ';
propertiesPolygon += '    </div>                                                                                                       ';
propertiesPolygon += '</div>                                                                                                           ';
propertiesPolygon += '<div class="properties_title">内部填充颜色</div>                                                                 ';
propertiesPolygon += '<div class="properties_cont">                                                                                    ';
propertiesPolygon += '    <div class="fill">                                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,0,255" class="a1"></a>                                                                             ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="255,0,0" class="a2"></a>                                                                             ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="255,255,0" class="a3"></a>                                                                             ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,128,0" class="a4 on"></a>                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="128,0,128" class="a5"></a>                                                                             ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,0,0" class="a6"></a>                                                                             ';
propertiesPolygon += '    </div>                                                                                                       ';
propertiesPolygon += '</div>                                                                                                           ';
propertiesPolygon += '<div class="properties_title">内部填充颜色透明度</div>                                                           ';
propertiesPolygon += '<div class="properties_cont">                                                                                    ';
propertiesPolygon += '     <div class="alpha">                                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="1" class="a1">10%</a>                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0.8" class="a1">25%</a>                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0.6" class="a1">50%</a>                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0.3" class="a1">75%</a>                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0.1" class="a1">85%</a>                                                                          ';
propertiesPolygon += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0" class="a1 on">100%</a>                                                                      ';
propertiesPolygon += '    </div>                                                                                                       ';
propertiesPolygon += '</div>                                                                                                           ';
propertiesPolygon += '<div class="properties_btn">                                                                                     ';
propertiesPolygon += '     <a href="javascript:void(0)" onclick="draw.save()">保存</a><a href="javascript:void(0)" onclick="draw.delSelect()">删除</a> ';
propertiesPolygon += '</div>                                                                                                           ';
propertiesPolygon += '</div>                                                                                                           ';

//============================
var propertiesLine = '';
propertiesLine += '<div class="select_properties">                                                                                  ';
propertiesLine += '<div class="select-header">                                                                                      ';
propertiesLine += '      <span class="select-current">样式属性选择</span>                                                           ';
propertiesLine += '      <span class="select-panel-close">                                                                          ';
propertiesLine += '            <a class="fa fa-close" href="javascript:void(0)" onclick="draw.tooltip.setPosition(undefined)"></a>             ';
propertiesLine += '      </span>                                                                                                    ';
propertiesLine += '</div>                                                                                                           ';
propertiesLine += '<div class="properties_title">外边框线颜色</div>                                                                 ';
propertiesLine += '<div class="properties_cont">                                                                                    ';
propertiesLine += '    <div class="stroke">                                                                                          ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,0,255" class="a1"></a>                                                                             ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="255,0,0" class="a2"></a>                                                                             ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="255,255,0" class="a3 on"></a>                                                                          ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,128,0" class="a4"></a>                                                                             ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="128,0,128" class="a5"></a>                                                                             ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="0,0,0" class="a6"></a>                                                                             ';
propertiesLine += '    </div>                                                                                                       ';
propertiesLine += '</div>                                                                                                           ';
propertiesLine += '<div class="properties_title">线粗细</div>                                                                 ';
propertiesLine += '<div class="properties_cont">                                                                                    ';
propertiesLine += '    <div class="width">                                                                                           ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="1" class="a1">1PX</a>                                                                       ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="2" class="a1 on">2PX</a>                                                                          ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="3" class="a1">3PX</a>                                                                          ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="4" class="a1">4PX</a>                                                                          ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="6" class="a1">6PX</a>                                                                          ';
propertiesLine += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="8" class="a1">8PX</a>                                                                          ';
propertiesLine += '    </div>                                                                                                       ';
propertiesLine += '</div>                                                                                                           ';
propertiesLine += '<div class="properties_btn">                                                                                     ';
propertiesLine += '     <a href="javascript:void(0)" onclick="draw.save()">保存</a><a href="javascript:void(0)" onclick="draw.delSelect()">删除</a> ';
propertiesLine += '</div>                                                                                                           ';
propertiesLine += '</div>                                                                                                           ';


var propertiesPoint = '';

propertiesPoint += '<div class="select_properties">                                                                                  ';
propertiesPoint += '<div class="select-header">                                                                                      ';
propertiesPoint += '      <span class="select-current">样式属性选择</span>                                                           ';
propertiesPoint += '      <span class="select-panel-close">                                                                          ';
propertiesPoint += '            <a class="fa fa-close" href="javascript:void(0)" onclick="draw.tooltip.setPosition(undefined)"></a>             ';
propertiesPoint += '      </span>                                                                                                    ';
propertiesPoint += '</div>                                                                                                           ';
propertiesPoint += '<div class="properties_title">图标样式</div>                                                                     ';
propertiesPoint += '<div class="properties_cont">                                                                                    ';
propertiesPoint += '     <div class="image">                                                                                        ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local1" class="a1 on"></a>                                                                             ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local2" class="a2"></a>                                                                             ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local3" class="a3"></a>                                                                            ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local4" class="a4"></a>                                                                            ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local5" class="a5"></a>                                                                            ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local6" class="a6"></a>                                                                            ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local7" class="a7"></a>                                                                             ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local8" class="a8"></a>                                                                             ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local9" class="a9"></a>                                                                             ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local10" class="a10"></a>                                                                             ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local11" class="a11"></a>                                                                             ';
propertiesPoint += '         <a href="javascript:void(0)" onclick="draw.setStyle(this)" value="local12" class="a12"></a>                                                                             ';
propertiesPoint += '    </div>                                                                                                       ';
propertiesPoint += '</div>                                                                                                           ';
propertiesPoint += '<div class="properties_btn">                                                                                     ';
propertiesPoint += '     <a href="javascript:void(0)" onclick="draw.save()">保存</a><a href="javascript:void(0)" onclick="draw.delSelect()">删除</a> ';
propertiesPoint += '</div>                                                                                                           ';
propertiesPoint += '</div>                                                                                                           ';



