
var  UIModuleId = 
{

	RCP_CARD_CFG : 1,

	RCP_TP_FP_EDIT : 2,

	RCP_LP_FP_EDIT : 3,

	RCP_TP_CARD_INPUT : 4,

	RCP_LP_CARD_INPUT : 5,

	RCP_LP_CASE_INPUT : 6,

	RCP_MATCH_WORKBENCH : 7,

	RCP_MATCH_CHECK : 8,

	RCP_MULTI_INFO : 9,

	RCP_WORK_FLOW_MGR : 10,

	WEB : 200,

	WEB_TP_CARD_INPUT : 201,

	WEB_LP_CARD_INPUT : 202,

	WEB_LP_CASE_INPUT : 203,

	WEB_WANTED_INPUT : 204,

	WEB_CAPTURE_INPUT : 205,

	WEB_TT_HITLOG_INPUT : 206,

	WEB_LL_HITLOG_INPUT : 207,

	WEB_LTL_HITLOG_INPUT : 208,

	WEB_TP_CARD_EDIT : 220,

	WEB_LP_CARD_EDIT : 221,

	WEB_LP_CASE_EDIT : 222,

	WEB_WANTED_EDIT : 223,

	WEB_CAPTURE_EDIT : 224,

	WEB_TT_HITLOG_EDIT : 225,

	WEB_LL_HITLOG_EDIT : 226,

	WEB_LTL_HITLOG_EDIT : 227,

	WEB_LTL_HITLOG_LIST : 228,
	
	WEB_TT_HITLOG_LIST : 229,
	
	WEB_LL_HITLOG_LIST : 230,
	
	WEB_TPCARD_LIST : 240,
	/**案件列表 配置**/
	WEB_LPCASE_LIST : 241,

	WEB_LPCARD_LIST : 242,

	WEB_MATCH_LIST : 243,

	WEB_HITLOG_LIST : 244,

	WEB_WANTED_LIST : 245,

	WEB_CAPTURE_LIST : 246,

	/** DNA信息 */
	WEB_DNA_STROAGE_LIST	: 247,

	/** DNA配送 */
	WEB_DNA_TRANSFERLIST	: 248,
	
	/** DNA接收 */
	WEB_DNA_RECEIVE_LIST	: 249,
	
	WEB_DNA_LIST	: 269,

	/** DNA回库 */
	WEB_DNA_BACK_LIST	: 250,
	
	WEB_MATCH_CHECK : 260,

	WEB_USER_MGR : 261,
	
	WEB_RMT_TP_CARD_UPLOAD_LIST		: 270,
	WEB_RMT_LP_CASE_UPLOAD_LIST		: 271,
	WEB_RMT_LP_CARD_UPLOAD_LIST		: 272,
	WEB_RMT_SVR_LIST				: 273,
	WEB_RMT_SVR_DB_LIST				: 274,
	WEB_RMT_TASK_LIST				: 275,
	WEB_RMT_TASK_HIST_LIST			: 276,
	WEB_RMT_QRY_SVR_LIST			: 277,
	WEB_RMT_CFG_LIST				: 278,
	WEB_RMT_ADD_CFG					: 279,
	WEB_RMT_ADD_SERVER				: 280,
	WEB_RMT_ADD_QRY_SERVER			: 281,
	WEB_RMT_GI_ENROLL_UPLOAD_LIST   : 282,
	
	WEB_NOMATCH_TP_LIST   		: 290,
	WEB_NOMATCHT_LP_LIST   		: 291,
	WEB_NOMATCH_TP_LP_LIST   	: 292,
	WEB_HOTEL_MONITOR_LIST   	: 293,
	WEB_LP_PERSON_LINK_LIST   	: 294,
	WEB_PERSON_CE_LINK_LIST   	: 295,

	WEB_MENU_LIST   			: 296,
	WEB_ROLE_LIST   			: 297,
	WEB_USER_SESSION_LIST   	: 298,
	
	WEB_TP_REPEAT_CARD_LIST 	: 299,


	WEB_MATCH_CHECK : 260,
	
	TP_TXT_INPUT : 450,

	LP_CASE_TXT_INPUT : 451,

	TP_TXT_EDIT : 452,

	C_LIVE_SCAN : 500,

	C_STD_INFO_COLLECT : 501,

    WEB_RMT_MATCH_PART_LIST : 806
}

