var ViewName =
{
		TP_CARD_VIEW			: "TP_CARD_VIEW",
		LP_CASE_VIEW			: "LP_CASE_VIEW",
		LP_CARD_VIEW			: "LP_CARD_VIEW",
		MATCH_VIEW				: "MATCH_VIEW",
		MP_ENROLL_FEEDBACK_VIEW	: "MP_ENROLL_FEEDBACK_VIEW",
		USER_VIEW				: "USER_VIEW",
		ROLE_VIEW				: "ROLE_VIEW",
		HS_PATH_FILE_VIEW		: "HS_PATH_FILE_VIEW",
		MIS_DNA_COLLECT_VIEW	: "MIS_DNA_COLLECT_VIEW",
		RMT_TP_UPLOAD_VIEW      : "RMT_TP_UPLOAD_VIEW",
		RMT_LP_CASE_UPLOAD_VIEW : "RMT_LP_CASE_UPLOAD_VIEW",
		RMT_LP_CARD_UPLOAD_VIEW : "RMT_LP_CARD_UPLOAD_VIEW"
}