
var  UserCUInfoCol = 
{
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   CREATE_UNIT_CODE : "CREATE_UNIT_CODE",
	
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_UNIT_CODE : "UPDATE_UNIT_CODE"
}

