
var  BpmAssignmentCol = 
{
   ID : "ID",
   DEST_DBID : "DEST_DBID",
   DB_TYPE : "DB_TYPE",
   EVENT_OBJ_ID : "EVENT_OBJ_ID",
   EVENT_TYPE : "EVENT_TYPE",
   RMT_FLAG : "RMT_FLAG",
   QRY_TYPE : "QRY_TYPE",
   BTY_FLAG : "BTY_FLAG",
   BPM_ID : "BPM_ID",
   CREATE_USER : "CREATE_USER",
   CREATE_TIME : "CREATE_TIME",
   CREATE_UNIT_CODE : "CREATE_UNIT_CODE",
   UPATE_USER : "UPATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_UNIT_CODE : "UPDATE_UNIT_CODE",
   IS_IN_BPM : "IS_IN_BPM",
   USER_NAME : "USER_NAME",
   USER_UNIT_CODE : "USER_UNIT_CODE",
   URID : "URID",
   USER_NAME_IS_WILD : "USER_NAME_IS_WILD",
   USER_UNIT_CODE_IS_WILD : "USER_UNIT_CODE_IS_WILD",
   CARD_NUM_WILD : "CARD_NUM_WILD"
}

var  BpmDefinationCol = 
{
   ID : "ID",
   NAME : "NAME",
   CREATE_USER : "CREATE_USER",
   CREATE_TIME : "CREATE_TIME",
   CREATE_UNIT_CODE : "CREATE_UNIT_CODE",
   UPATE_USER : "UPATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_UNIT_CODE : "UPDATE_UNIT_CODE",
   DEF_TEXT : "DEF_TEXT",
   IS_PUBLISHED : "IS_PUBLISHED",
   BPM_KEY : "BPM_KEY"
}

var  BpmDeploymentCol = 
{
   ID : "ID",
   BPM_ID : "BPM_ID",
   DEPLOY_TIME : "DEPLOY_TIME",
   DEF_TEXT : "DEF_TEXT"
}

