
var  CapturedAuditLogCol = 
{
   ID : "ID",
   CAPTURED_ID : "CAPTURED_ID",
   TASK_TYPE : "TASK_TYPE",
   AUDIT_USER : "AUDIT_USER",
   AUDIT_UNIT_CODE : "AUDIT_UNIT_CODE",
   AUDIT_DATE : "AUDIT_DATE",
   AUDIT_RESULT : "AUDIT_RESULT",
   AUDIT_COMMENTS : "AUDIT_COMMENTS"
}

var  CapturedAuditTaskCol = 
{
   ID : "ID",
   TASK_TYPE : "TASK_TYPE",
   CREATE_TIME : "CREATE_TIME",
   PRIORITY : "PRIORITY",
   STATUS : "STATUS",
   BPM_ID : "BPM_ID",
   WORKING_TIME : "WORKING_TIME"
}

var  CapturedCaseLinkCol = 
{
   ID : "ID",
   CASE_ID : "CASE_ID"
}

var  CapturedPersonLinkCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID"
}

var  CapturedPersonMainCol = 
{
   ID : "ID",
   CAPTURE_STATUS : "CAPTURE_STATUS",
   CREATE_USER : "CREATE_USER",
   CREATE_TIME : "CREATE_TIME",
   CREATE_UNIT_CODE : "CREATE_UNIT_CODE",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_UNIT_CODE : "UPDATE_UNIT_CODE",
   CAPTURE_DATE : "CAPTURE_DATE",
   CAPTURE_METHOD : "CAPTURE_METHOD",
   CAPTURE_ADDRESS_CODE : "CAPTURE_ADDRESS_CODE",
   CAPTURE_ADDRESS : "CAPTURE_ADDRESS",
   CAPTURE_UNIT_CODE : "CAPTURE_UNIT_CODE",
   CAPTURE_UNIT_NAME : "CAPTURE_UNIT_NAME",
   CAPTURE_UNIT_TYPE : "CAPTURE_UNIT_TYPE",
   CAPTURE_FILL_IN_USER : "CAPTURE_FILL_IN_USER",
   CAPTURE_FILL_IN_DATE : "CAPTURE_FILL_IN_DATE",
   REQ_ENROLL_USER : "REQ_ENROLL_USER",
   REQ_ENROLL_DATE : "REQ_ENROLL_DATE",
   REQ_APPROVED_BY : "REQ_APPROVED_BY",
   REQ_APPROVED_DATE : "REQ_APPROVED_DATE",
   REQ_UNIT_CODE : "REQ_UNIT_CODE",
   REQ_UNIT_NAME : "REQ_UNIT_NAME",
   GAB_ZT_CARD_NO : "GAB_ZT_CARD_NO"
}

