
var  CodeTableCodeCol = 
{
   CODE_TABLE_NAME : "CODE_TABLE_NAME",
   CODE : "CODE",
   INPUT_CODE : "INPUT_CODE",
   VALUE : "VALUE",
   DESCRIPTION : "DESCRIPTION",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_TIME : "UPDATE_TIME"
}

var  CodeTableCodeMapCol = 
{
   CODE_TABLE_NAME : "CODE_TABLE_NAME",
   OLD_CODE : "OLD_CODE",
   OLD_VALUE : "OLD_VALUE",
   NEW_CODE : "NEW_CODE",
   NEW_VALUE : "NEW_VALUE",
   DESCRIPTION : "DESCRIPTION",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

var  CodeTableOpLogCol = 
{
   ID : "ID",
   CODE_TABLE_NAME : "CODE_TABLE_NAME",
   OP_CODE : "OP_CODE",
   CODE : "CODE",
   OLD_VALUE : "OLD_VALUE",
   NEW_VALUE : "NEW_VALUE",
   DESCRIPTION : "DESCRIPTION",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

