
var  DataGeneralLinkCol = 
{
   DATA_1_TYPE : "DATA_1_TYPE",
   DATA_1_ID : "DATA_1_ID",
   DATA_2_TYPE : "DATA_2_TYPE",
   DATA_2_ID : "DATA_2_ID",
   LINK_TYPE : "LINK_TYPE",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   COMMENTS : "COMMENTS",
   INI_ENROLL_USER : "INI_ENROLL_USER",
   INI_ENROLL_UNIT_CODE : "INI_ENROLL_UNIT_CODE",
   INI_ENROLL_TIME : "INI_ENROLL_TIME"
}

var  LPCardGroupCol = 
{
   ID : "ID",
   GROUP_NUM : "GROUP_NUM",
   DESCRIPTION : "DESCRIPTION",
   CREATE_USER : "CREATE_USER",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   INI_ENROLL_USER : "INI_ENROLL_USER",
   INI_ENROLL_UNIT_CODE : "INI_ENROLL_UNIT_CODE",
   INI_ENROLL_TIME : "INI_ENROLL_TIME"
}

var  LPCardGroupLinkCol = 
{
   CARD_ID : "CARD_ID",
   GROUP_ID : "GROUP_ID",
   CREATE_USER : "CREATE_USER",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   INI_ENROLL_USER : "INI_ENROLL_USER",
   INI_ENROLL_UNIT_CODE : "INI_ENROLL_UNIT_CODE",
   INI_ENROLL_TIME : "INI_ENROLL_TIME"
}

var  LPCardPersonLinkCol = 
{
   CARD_ID : "CARD_ID",
   UNI_PERSON_ID : "UNI_PERSON_ID",
   FGP : "FGP",
   CREATE_USER : "CREATE_USER",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   INI_ENROLL_USER : "INI_ENROLL_USER",
   INI_ENROLL_UNIT_CODE : "INI_ENROLL_UNIT_CODE",
   INI_ENROLL_TIME : "INI_ENROLL_TIME"
}

var  LPCardUnknownPersonLinkCol = 
{
   CARD_ID : "CARD_ID",
   UNKNOWN_PERSON_ID : "UNKNOWN_PERSON_ID",
   FGP : "FGP",
   CREATE_USER : "CREATE_USER",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   INI_ENROLL_USER : "INI_ENROLL_USER",
   INI_ENROLL_UNIT_CODE : "INI_ENROLL_UNIT_CODE",
   INI_ENROLL_TIME : "INI_ENROLL_TIME"
}

var  LPCeGroupCol = 
{
   ID : "ID",
   GROUP_NAME : "GROUP_NAME",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   COMMENTS : "COMMENTS",
   INI_ENROLL_USER : "INI_ENROLL_USER",
   INI_ENROLL_TIME : "INI_ENROLL_TIME",
   INI_ENROLL_UNIT_CODE : "INI_ENROLL_UNIT_CODE"
}

var  LPCeGroupItemCol = 
{
   CASE_ID : "CASE_ID",
   GROUP_ID : "GROUP_ID",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   COMMENTS : "COMMENTS",
   INI_ENROLL_USER : "INI_ENROLL_USER",
   INI_ENROLL_TIME : "INI_ENROLL_TIME",
   INI_ENROLL_UNIT_CODE : "INI_ENROLL_UNIT_CODE",
   MERGE_TYPE : "MERGE_TYPE"
}

var  LPUnknownPersonCol = 
{
   ID : "ID",
   DESCRIPTION : "DESCRIPTION",
   CREATE_USER : "CREATE_USER",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   INI_ENROLL_USER : "INI_ENROLL_USER",
   INI_ENROLL_UNIT_CODE : "INI_ENROLL_UNIT_CODE",
   INI_ENROLL_TIME : "INI_ENROLL_TIME"
}

var  NonMatchLPCardsCol = 
{
   LP_CARD_ID_1 : "LP_CARD_ID_1",
   LP_CARD_ID_2 : "LP_CARD_ID_2",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   INI_ENROLL_TIME : "INI_ENROLL_TIME",
   INI_ENROLL_USER : "INI_ENROLL_USER"
}

var  NonMatchPersonsCol = 
{
   UNI_PERSON_ID_1 : "UNI_PERSON_ID_1",
   UNI_PERSON_ID_2 : "UNI_PERSON_ID_2",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   INI_ENROLL_TIME : "INI_ENROLL_TIME",
   INI_ENROLL_USER : "INI_ENROLL_USER"
}

var  NonMatchTPLPCardsCol = 
{
   LP_CARD_ID : "LP_CARD_ID",
   UNI_PERSON_ID : "UNI_PERSON_ID",
   FGP : "FGP",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   INI_ENROLL_TIME : "INI_ENROLL_TIME",
   INI_ENROLL_USER : "INI_ENROLL_USER"
}

var  PersonCELinkCol = 
{
   PERSON_ID : "PERSON_ID",
   CE_ID : "CE_ID",
   LINK_TYPE : "LINK_TYPE",
   COMMENTS : "COMMENTS",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   INI_ENROLL_USER : "INI_ENROLL_USER",
   INI_ENROLL_UNIT_CODE : "INI_ENROLL_UNIT_CODE",
   INI_ENROLL_TIME : "INI_ENROLL_TIME"
}

