
var  CardMexErrLogCol = 
{
   ID : "ID",
   PRINT_TYPE : "PRINT_TYPE",
   CARD_ID : "CARD_ID",
   CARD_NUM : "CARD_NUM",
   CREATE_TIME : "CREATE_TIME",
   TEN_STRING : "TEN_STRING",
   TASK_OPT : "TASK_OPT",
   ERROR_CODE : "ERROR_CODE",
   RET_VALUE : "RET_VALUE",
   DLL_VERSION : "DLL_VERSION",
   BTY : "BTY",
   FGP : "FGP",
   VID : "VID",
   CID : "CID",
   METHOD_ID : "METHOD_ID",
   VENDOR_ID : "VENDOR_ID",
   PRODUCT_ID : "PRODUCT_ID",
   COMPUTER_NAME : "COMPUTER_NAME",
   MEX_APP_VERSION : "MEX_APP_VERSION",
   DLL_NAME : "DLL_NAME",
   OP_TYPE : "OP_TYPE",
   ERR_INFO : "ERR_INFO",
   TASK_GEN_TIME : "TASK_GEN_TIME"
}

var  CardMexLogCol = 
{
   ID : "ID",
   PRINT_TYPE : "PRINT_TYPE",
   CARD_ID : "CARD_ID",
   CARD_NUM : "CARD_NUM",
   FINISH_TIME : "FINISH_TIME",
   MEX_TIME_USED : "MEX_TIME_USED",
   TEN_STRING : "TEN_STRING",
   STATUS : "STATUS",
   TASK_OPT : "TASK_OPT",
   COMPUTER_NAME : "COMPUTER_NAME",
   TASK_GEN_TIME : "TASK_GEN_TIME"
}

var  LiveRescanLogCol = 
{
   ID : "ID",
   QUAL_CHECK_QUE_ID : "QUAL_CHECK_QUE_ID",
   CARD_ID : "CARD_ID",
   CARD_NUM : "CARD_NUM",
   INPUT_USER_NAME : "INPUT_USER_NAME",
   INPUT_UNIT_CODE : "INPUT_UNIT_CODE",
   INPUT_DATE_TIME : "INPUT_DATE_TIME",
   FINISH_USER_NAME : "FINISH_USER_NAME",
   FINISH_UNIT_CODE : "FINISH_UNIT_CODE",
   FINISH_DATE_TIME : "FINISH_DATE_TIME",
   RESULT : "RESULT",
   RESCAN_TEN_STRING : "RESCAN_TEN_STRING",
   INSTANCE_ID : "RESCAN_LOG_ID",
   IS_RESCAN_TIME_OUT : "IS_RESCAN_TIME_OUT",
   TASK_GEN_TIME : "TASK_GEN_TIME"
}

var  LiveScanQualCheckLogCol = 
{
   ID : "ID",
   QUAL_CHECK_QUE_ID : "QUAL_CHECK_QUE_ID",
   CARD_ID : "CARD_ID",
   CARD_NUM : "CARD_NUM",
   INPUT_USER_NAME : "INPUT_USER_NAME",
   INPUT_UNIT_CODE : "INPUT_UNIT_CODE",
   INPUT_DATE_TIME : "INPUT_DATE_TIME",
   CHECK_USER_NAME : "CHECK_USER_NAME",
   CHECK_UNIT_CODE : "CHECK_UNIT_CODE",
   CHECK_DATE_TIME : "CHECK_DATE_TIME",
   CHECK_RESULT : "CHECK_RESULT",
   MAIN_LOW_QUALITY_REASON : "MAIN_LOW_QUALITY_REASON",
   LOW_QUALITY_REASON : "LOW_QUALITY_REASON",
   CHECK_TEN_STRING : "CHECK_TEN_STRING",
   RESCAN_TEN_STRING : "RESCAN_TEN_STRING",
   CHECK_TYPE : "CHECK_TYPE",
   CHECKED_ITEMS : "CHECKED_ITEMS",
   INSTANCE_ID : "INSTANCE_ID",
   IS_QUAL_CHECK_TIME_OUT : "IS_QUAL_CHECK_TIME_OUT",
   TASK_GEN_TIME : "TASK_GEN_TIME"
}

var  LLHitlogAuditLogCol = 
{
   ID : "ID",
   HITLOG_ID : "HITLOG_ID",
   TASK_TYPE : "TASK_TYPE",
   AUDITER : "AUDITER",
   AUDITER_ID : "AUDITER_ID",
   AUDIT_DATE : "AUDIT_DATE",
   AUDITER_UNIT_CODE : "AUDITER_UNIT_CODE",
   AUDITER_UNIT_NAME : "AUDITER_UNIT_NAME",
   AUDIT_RESULT : "AUDIT_RESULT",
   AUDIT_COMMENTS : "AUDIT_COMMENTS",
   TASK_GEN_TIME : "TASK_GEN_TIME"
}

var  LPCardQualCheckLogCol = 
{
   ID : "ID",
   CARD_ID : "CARD_ID",
   CASE_NUM : "CASE_NUM",
   CARD_NUM : "CARD_NUM",
   CREATE_TIME : "CREATE_TIME",
   CHECKER : "CHECKER",
   CHECKER_UNIT_CODE : "CHECKER_UNIT_CODE",
   QUAL_CHECK_RESULT : "QUAL_CHECK_RESULT",
   MAIN_LOW_QUALITY_REASON : "MAIN_LOW_QUALITY_REASON",
   LOW_QUALITY_REASON : "LOW_QUALITY_REASON",
   COMMENTS : "COMMENTS",
   TASK_GEN_TIME : "TASK_GEN_TIME"
}

var  LTLHitlogAuditLogCol = 
{
   ID : "ID",
   HITLOG_ID : "HITLOG_ID",
   TASK_TYPE : "TASK_TYPE",
   AUDITER : "AUDITER",
   AUDITER_ID : "AUDITER_ID",
   AUDIT_DATE : "AUDIT_DATE",
   AUDITER_UNIT_CODE : "AUDITER_UNIT_CODE",
   AUDITER_UNIT_NAME : "AUDITER_UNIT_NAME",
   AUDIT_RESULT : "AUDIT_RESULT",
   AUDIT_COMMENTS : "AUDIT_COMMENTS",
   TASK_GEN_TIME : "TASK_GEN_TIME"
}

var  TableColUpdateLogCol = 
{
   ID : "ID",
   EVENT_OBJECT_ID : "EVENT_OBJECT_ID",
   EVENT_TYPE : "EVENT_TYPE",
   TABLE_NAME : "TABLE_NAME",
   COL_NAME : "COL_NAME",
   REC_ID : "REC_ID",
   REC_KEY_NUM : "REC_KEY_NUM",
   OLD_VALUE : "OLD_VALUE",
   NEW_VALUE : "NEW_VALUE",
   OP_USER : "OP_USER",
   OP_UNIT_CODE : "OP_UNIT_CODE",
   OP_TIME : "OP_TIME",
   OP_TYPE : "OP_TYPE"
}

var  TableOperLogCol = 
{
   ID : "ID",
   EVENT_OBJECT_ID : "EVENT_OBJECT_ID",
   EVENT_TYPE : "EVENT_TYPE",
   TABLE_NAME : "TABLE_NAME",
   REC_ID : "REC_ID",
   REC_KEY_NUM : "REC_KEY_NUM",
   OP_USER : "OP_USER",
   OP_UNIT_CODE : "OP_UNIT_CODE",
   OP_TIME : "OP_TIME",
   OP_TYPE : "OP_TYPE",
   OP_CTX : "OP_CTX"
}

var  TableSelectLogCol = 
{
   ID : "ID",
   EVENT_OBJ_ID : "EVENT_OBJ_ID",
   EVENT_TYPE : "EVENT_TYPE",
   TABLE_NAME : "TABLE_NAME",
   SQL_STMT : "SQL_STMT",
   MAX_RESULT_CNT : "MAX_RESULT_CNT",
   RESULT_OFFSET : "RESULT_OFFSET",
   PROJ_COLS : "PROJ_COLS",
   OP_USER : "OP_USER",
   OP_UNIT_CODE : "OP_UNIT_CODE",
   OP_TIME : "OP_TIME",
   OP_TYPE : "OP_TYPE"
}

var  TPCardQualCheckTaskLogCol = 
{
   ID : "ID",
   CARD_ID : "CARD_ID",
   CARD_NUM : "CARD_NUM",
   CHECK_RESULT : "CHECK_RESULT",
   MAIN_LOW_QUALITY_REASON : "MAIN_LOW_QUALITY_REASON",
   LOW_QUALITY_REASON : "LOW_QUALITY_REASON",
   CARD_QUALITY : "CARD_QUALITY",
   NEED_CHECK_TEN_STRING : "NEED_CHECK_TEN_STRING",
   CHECKED_ITEMS : "CHECKED_ITEMS",
   CHECK_TIME : "CHECK_TIME",
   CHECKER : "CHECKER",
   CHECKER_UNIT_CODE : "CHECKER_UNIT_CODE",
   TASK_GEN_TIME : "TASK_GEN_TIME"
}

var  TPTextInputTaskLogCol = 
{
   ID : "ID",
   CARD_ID : "CARD_ID",
   INPUT_TIME_USED : "INPUT_TIME_USED",
   TEXT_INPUT_TIME : "TEXT_INPUT_TIME",
   TEXT_INPUT_BY : "TEXT_INPUT_BY",
   USER_UNIT_CODE : "USER_UNIT_CODE",
   TASK_GEN_TIME : "TASK_GEN_TIME"
}

var  TTHitlogAuditLogCol = 
{
   ID : "ID",
   HITLOG_ID : "HITLOG_ID",
   TASK_TYPE : "TASK_TYPE",
   AUDITER : "AUDITER",
   AUDITER_ID : "AUDITER_ID",
   AUDIT_DATE : "AUDIT_DATE",
   AUDITER_UNIT_CODE : "AUDITER_UNIT_CODE",
   AUDITER_UNIT_NAME : "AUDITER_UNIT_NAME",
   AUDIT_RESULT : "AUDIT_RESULT",
   AUDIT_COMMENTS : "AUDIT_COMMENTS",
   TASK_GEN_TIME : "TASK_GEN_TIME"
}

var  UserLoginLogCol = 
{
   ID : "ID",
   USER_ID : "USER_ID",
   COMPUTER_IP : "COMPUTER_IP",
   COMPUTER_NAME : "COMPUTER_NAME",
   OP_TIME : "OP_TIME",
   OP_TYPE : "OP_TYPE"
}

var  WantedPersonAuditLogCol = 
{
   ID : "ID",
   WANTED_ID : "WANTED_ID",
   TASK_TYPE : "TASK_TYPE",
   AUDIT_USER : "AUDIT_USER",
   AUDIT_UNIT_CODE : "AUDIT_UNIT_CODE",
   AUDIT_DATE : "AUDIT_DATE",
   AUDIT_RESULT : "AUDIT_RESULT",
   AUDIT_COMMENTS : "AUDIT_COMMENTS",
   TASK_GEN_TIME : "TASK_GEN_TIME"
}

