
var  CaseBreakInfoCol = 
{
   ID : "ID",
   BREAK_DATE : "BREAK_DATE",
   BREAK_DATE_TYPE_CODE : "BREAK_DATE_TYPE_CODE",
   BREAK_METHOD_CODE : "BREAK_METHOD_CODE",
   BREAK_METHOD_DESC : "BREAK_METHOD_DESC"
}

var  CaseEventCol = 
{
   ID : "ID",
   DBID_MASK : "DBID",
   DBID : "DBID",
   CE_TYPE : "CE_TYPE",
   CE_NUM : "CE_NUM",
   ABIS_CE_NUM:"ABIS_CE_NUM",
    SCENE_INVEST_NUM:"SCENE_INVEST_NUM",
   CE_NAME : "CE_NAME",
    POLICE_NUM : "POLICE_NUM",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   CREATE_UNIT_CODE : "CREATE_UNIT_CODE",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_UNIT_CODE : "UPDATE_UNIT_CODE",
   CE_STATUS : "CE_STATUS",
   COMMENTS : "COMMENTS"
}

var  CaseExtractInfoCol = 
{
   ID : "ID",
   EXTRACT_DATE : "EXTRACT_DATE",
   EXTRACTOR_1 : "EXTRACTOR_1",
   EXTRACTOR_2 : "EXTRACTOR_2",
   EXTRACTOR_3 : "EXTRACTOR_3",
   EXTRACT_UNIT_CODE : "EXTRACT_UNIT_CODE",
   EXTRACT_UNIT_NAME : "EXTRACT_UNIT_NAME",
   COMMENTS : "COMMENTS"
}

var  CaseRegisterInfoCol = 
{
   ID : "ID",
   REGI_UNIT_CODE : "REGI_UNIT_CODE",
   REGI_UNIT_NAME : "REGI_UNIT_NAME",
   REGI_APPROVER : "REGI_APPROVER",
   REGI_TIME : "REGI_TIME"
}

var  CEAcceptInfoCol = 
{
   ID : "ID",
   ACCEPT_UNIT_CODE : "ACCEPT_UNIT_CODE",
   ACCEPT_UNIT_NAME : "ACCEPT_UNIT_NAME",
   ACCEPT_OPERATOR : "ACCEPT_OPERATOR",
   ACCEPT_PLACE : "ACCEPT_PLACE",
   ACCEPT_TIME : "ACCEPT_TIME",
   COMMENTS : "COMMENTS"
}

var  CEBasicInfoCol = 
{
   ID : "ID",
   CE_CLASS_CODE_1 : "CE_CLASS_CODE_1",
   CE_CLASS_CODE_2 : "CE_CLASS_CODE_2",
   CE_CLASS_CODE_3 : "CE_CLASS_CODE_3",
   CE_OCCUR_DATE : "CE_OCCUR_DATE",
   CE_OCCUR_PLACE_CODE : "CE_OCCUR_PLACE_CODE",
   CE_OCCUR_PLACE : "CE_OCCUR_PLACE",
   HAS_PERSON_KILLED : "HAS_PERSON_KILLED",
   PERSON_KILLED_CNT : "PERSON_KILLED_CNT",
   SUPERVISE_LEVEL : "SUPERVISE_LEVEL",
   CASE_LOSS : "CASE_LOSS",
   CE_COMMENTS : "CE_COMMENTS",
	
   CE_SUSPICIOUS_AREA_CODE_1 : "CE_SUSPICIOUS_AREA_CODE_1",
   CE_SUSPICIOUS_AREA_CODE_2 : "CE_SUSPICIOUS_AREA_CODE_2",
   CE_SUSPICIOUS_AREA_CODE_3 : "CE_SUSPICIOUS_AREA_CODE_3",
   CE_PREMIUM : "CE_PREMIUM"
}

var  CECancelInfoCol = 
{
   ID : "ID",
   CANCEL_DATE : "CANCEL_DATE",
   CANCEL_REASON_CODE : "CANCEL_REASON_CODE"
}

var  LPCardDBCol = 
{
   DBID : "DBID",
   CARD_ID : "CARD_ID",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

var  LPCardEnrollInfoCol = 
{
   ID : "ID",
   INI_ENROLL_USER : "INI_ENROLL_USER",
   INI_ENROLL_UNIT_CODE : "INI_ENROLL_UNIT_CODE",
   INI_SYS_ID : "INI_SYS_ID",
   INI_ENROLL_TIME : "INI_ENROLL_TIME",
   ENROLL_TYPE : "ENROLL_TYPE",
   OBJECT_TYPE : "OBJECT_TYPE",
   DEVICE_TYPE : "DEVICE_TYPE",
   ENROLL_SITE_ID : "ENROLL_SITE_ID"
}

var  LPCardHitInfoCol = 
{
   ID : "ID",
   CHECKER : "CHECKER",
   CHECKER_NAME : "CHECKER_NAME",
   CHECKER_UNIT_CODE : "CHECKER_UNIT_CODE",
   CHECKER_UNIT_NAME : "CHECKER_UNIT_NAME",
   CHECK_TIME : "CHECK_TIME",
   TP_CARD_ID : "TP_CARD_ID",
   TP_CARD_NO : "TP_CARD_NO",
   TP_PERSON_NO : "TP_PERSON_NO",
   TP_PERSON_NAME : "TP_PERSON_NAME",
   TP_PERSON_SEX_CODE : "TP_PERSON_SEX_CODE",
   TP_PERSON_SHENFEN_ID : "TP_PERSON_SHENFEN_ID",
   TP_PERSON_BIRTH_DATE : "TP_PERSON_BIRTH_DATE",
   FGP : "FGP",
   COMMENTS : "COMMENTS",
   TP_PRINT_USER_NAME : "TP_PRINT_USER_NAME",
   TP_PRINT_DATE : "TP_PRINT_DATE",
   TP_PRINT_UNIT_CODE : "TP_PRINT_UNIT_CODE",
   TP_PRINT_UNIT_NAME : "TP_PRINT_UNIT_NAME"
}

var  LPCardInfoCol = 
{
   ID : "ID",
   DBID_MASK : "DBID_MASK",
   CE_ID : "CE_ID",
   CARD_UUID : "CARD_UUID",
   BTY : "BTY",
   SEQ_NO : "SEQ_NO",
   CARD_NUM : "CARD_NUM",
   HAS_TP_MATCH : "HAS_TP_MATCH",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   COMMENTS : "COMMENTS"
}

var  LPCardLobCol = 
{
   ID : "ID",
   CARD_ID : "CARD_ID",
   DATA_TYPE : "DATA_TYPE",
   BTY : "BTY",
   CID : "CID",
   GID : "GID",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_TIME : "UPDATE_TIME",
   STORAGE_TYPE : "STORAGE_TYPE"
}

var  LPCardLobDBItemCol = 
{
   ID : "ID",
   ITEM_INDEX : "ITEM_INDEX",
   UPDATE_TIME : "UPDATE_TIME",
   DATA_FMT : "DATA_FMT",
   DATA_CRC : "DATA_CRC",
   DATA : "DATA"
}

var  LPCardTextCol = 
{
   ID : "ID",
   IS_NAMELESS_CORPSE : "IS_NAMELESS_CORPSE",
   NAMELESS_CORPSE_ID : "NAMELESS_CORPSE_ID",
   LEFT_LOCATION : "LEFT_LOCATION",
   START_FGP : "START_FGP",
   END_FGP : "END_FGP",
   MNT_EXTRACT_METHOD : "MNT_EXTRACT_METHOD",
   RIDGE_COLOR : "RIDGE_COLOR",
   SENDER_ID : "SENDER_ID",
   CAND_FGPS : "CAND_FGPS"
}

var  LPCeDBCol = 
{
   DBID : "DBID",
   CE_ID : "CE_ID",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

