
var  MatchPartitionCol = 
{
   ID : "ID",
   PART_UUID : "PART_UUID",
   DBID_MASK : "DBID_MASK",
   MATCH_ELEMENTS : "MATCH_ELEMENTS",
//   BTY : "BTY",
//   FGP : "FGP",
//   VID : "VID",
//   CID : "CID",
//   GID : "GID",
   MATCH_MNT_FMT : "MATCH_MNT_FMT",
   PRINT_TYPE : "PRINT_TYPE",
   UNIT_CODE : "UNIT_CODE",
   CREATE_USER : "CREATE_USER",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
//   IS_DISABLED : "IS_DISABLED",
   SRC_TP_MATCH_METHOD_ID : "SRC_TP_MATCH_METHOD_ID",
   SRC_LP_MATCH_METHOD_ID : "SRC_LP_MATCH_METHOD_ID",
   DESCRIPTION : "DESCRIPTION",
   PART_TYPE : "PART_TYPE",
//   SERVER_PID : "SERVER_PID",
//   SID_STEP_SIZE : "SID_STEP_SIZE",
   PID_MASK : "PID_MASK",
   BTY_MASK : "BTY_MASK",
   SUB_PID_MASK : "SUB_PID_MASK"
}

var  RmtMatchPartitionCol = 
{
   LOC_PART_ID : "LOC_PART_ID",
   SVR_PART_ID : "SVR_PART_ID",
   SVR_UNIT_CODE : "SVR_UNIT_CODE",
   SVR_PART_NAME : "SVR_PART_NAME"
}

var  VirtMatchPartMntLevelCol = 
{
   VIRT_PART_ID : "VIRT_PART_ID",
   VIRT_MNT_LEVEL : "VIRT_MNT_LEVEL",
   REAL_PART_ID : "REAL_PART_ID",
   REAL_MNT_LEVEL : "REAL_MNT_LEVEL"
}

