
var  MntSummaryIniSyncInfoCol = 
{
   ID : "ID",
   LAST_LOB_ID : "LAST_LOB_ID",
   LAST_UPDATE_TIME : "LAST_UPDATE_TIME",
   START_SYNC_LOG_SCN : "START_SYNC_LOG_SCN"
}

var  MntSummaryLPFingerCol = 
{
   ID : "ID",
   CARD_ID : "CARD_ID",
   CID : "CID",
   GID : "GID",
   IMG_WIDTH : "IMG_WIDTH",
   IMG_HEIGHT : "IMG_HEIGHT",
   IMG_RESOLUTION : "IMG_RESOLUTION",
   MNT_COUNT : "MNT_COUNT",
   TOTAL_CORE_COUNT : "TOTAL_CORE_COUNT",
   TOTAL_DELTA_COUNT : "TOTAL_DELTA_COUNT",
   MNT_QUALITY : "MNT_QUALITY",
   IMG_QUALITY : "IMG_QUALITY",
   MAJOR_PATTERN : "MAJOR_PATTERN",
   MINOR_PATTERN : "MINOR_PATTERN",
   HAS_UPPER_CORE : "HAS_UPPER_CORE",
   HAS_LOWER_CORE : "HAS_LOWER_CORE",
   HAS_LEFT_DELTA : "HAS_LEFT_DELTA",
   HAS_RIGHT_DELTA : "HAS_RIGHT_DELTA",
   PATTERN_CORE_COUNT : "PATTERN_CORE_COUNT",
   PATTERN_DELTA_COUNT : "PATTERN_DELTA_COUNT",
   CAND_FGPS : "CAND_FGPS",
   HAS_UDF_DATA : "HAS_UDF_DATA",
   HAS_RIDGE_LINE_DATA : "HAS_RIDGE_LINE_DATA",
   DATA_LENGTH : "DATA_LENGTH"
}

var  MntSummaryLPPalmCol = 
{
   ID : "ID",
   CARD_ID : "CARD_ID",
   CID : "CID",
   GID : "GID",
   IMG_WIDTH : "IMG_WIDTH",
   IMG_HEIGHT : "IMG_HEIGHT",
   IMG_RESOLUTION : "IMG_RESOLUTION",
   MNT_COUNT : "MNT_COUNT",
   MNT_QUALITY : "MNT_QUALITY",
   IMG_QUALITY : "IMG_QUALITY",
   PATTERN_CORE_COUNT : "PATTERN_CORE_COUNT",
   PATTERN_DELTA_COUNT : "PATTERN_DELTA_COUNT",
   HAS_WRIST_DELTA : "HAS_WRIST_DELTA",
   FINGER_ROOT_DELTA_COUNT : "FINGER_ROOT_DELTA_COUNT",
   HAS_QJZW : "HAS_QJZW",
   CAND_FGPS : "CAND_FGPS",
   HAS_UDF_DATA : "HAS_UDF_DATA",
   HAS_RIDGE_LINE_DATA : "HAS_RIDGE_LINE_DATA",
   DATA_LENGTH : "DATA_LENGTH"
}

var  MntSummarySyncStatusCol = 
{
   ID : "ID",
   STATUS : "STATUS",
   LAST_SYNC_TIME : "LAST_SYNC_TIME",
   LAST_SYNC_LOG_SCN : "LAST_SYNC_LOG_SCN",
   INI_SYNC_TIME : "INI_SYNC_TIME"
}

var  MntSummaryTPFingerCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   FGP : "FGP",
   VID : "VID",
   CID : "CID",
   GID : "GID",
   IMG_WIDTH : "IMG_WIDTH",
   IMG_HEIGHT : "IMG_HEIGHT",
   IMG_RESOLUTION : "IMG_RESOLUTION",
   MNT_COUNT : "MNT_COUNT",
   TOTAL_CORE_COUNT : "TOTAL_CORE_COUNT",
   TOTAL_DELTA_COUNT : "TOTAL_DELTA_COUNT",
   MNT_QUALITY : "MNT_QUALITY",
   IMG_QUALITY : "IMG_QUALITY",
   MAJOR_PATTERN : "MAJOR_PATTERN",
   MINOR_PATTERN : "MINOR_PATTERN",
   HAS_UPPER_CORE : "HAS_UPPER_CORE",
   HAS_LOWER_CORE : "HAS_LOWER_CORE",
   HAS_LEFT_DELTA : "HAS_LEFT_DELTA",
   HAS_RIGHT_DELTA : "HAS_RIGHT_DELTA",
   PATTERN_CORE_COUNT : "PATTERN_CORE_COUNT",
   PATTERN_DELTA_COUNT : "PATTERN_DELTA_COUNT",
   HAS_UDF_DATA : "HAS_UDF_DATA",
   HAS_RIDGE_LINE_DATA : "HAS_RIDGE_LINE_DATA",
   DATA_LENGTH : "DATA_LENGTH"
}

var  MntSummaryTPPalmCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   FGP : "FGP",
   VID : "VID",
   CID : "CID",
   GID : "GID",
   IMG_WIDTH : "IMG_WIDTH",
   IMG_HEIGHT : "IMG_HEIGHT",
   IMG_RESOLUTION : "IMG_RESOLUTION",
   MNT_COUNT : "MNT_COUNT",
   MNT_QUALITY : "MNT_QUALITY",
   IMG_QUALITY : "IMG_QUALITY",
   PATTERN_CORE_COUNT : "PATTERN_CORE_COUNT",
   PATTERN_DELTA_COUNT : "PATTERN_DELTA_COUNT",
   HAS_WRIST_DELTA : "HAS_WRIST_DELTA",
   FINGER_ROOT_DELTA_COUNT : "FINGER_ROOT_DELTA_COUNT",
   HAS_QJZW : "HAS_QJZW",
   HAS_UDF_DATA : "HAS_UDF_DATA",
   HAS_RIDGE_LINE_DATA : "HAS_RIDGE_LINE_DATA",
   DATA_LENGTH : "DATA_LENGTH"
}

