
var  CprAlgPropCol = 
{
   CPR_ALG_ID : "CPR_ALG_ID",
   BTY : "BTY",
   PRINT_TYPE : "PRINT_TYPE",
   MIN_CPR_RATIO : "MIN_CPR_RATIO",
   MAX_CPR_RATIO : "MAX_CPR_RATIO",
   DEFAULT_CPR_RATIO : "DEFAULT_CPR_RATIO",
   DEFAULT_LOB_FORMAT_ID : "DEFAULT_LOB_FORMAT_ID",
   SUPPORTED_LOB_FORMAT_ID : "SUPPORTED_LOB_FORMAT_ID",
   DESCRIPTION : "DESCRIPTION"
}


var  DBGroupCfgCol = 
{
   ID : "ID",
   DBID : "DBID",
   PRINT_TYPE : "PRINT_TYPE",
   BTY : "BTY",
   GID : "GID",
   DEFAULT_MNT_FMT : "DEFAULT_MNT_FMT",
   DEFAULT_MEX_METHOD : "DEFAULT_MEX_METHOD",
   DEFAULT_MEX_VENDOR_ID : "DEFAULT_MEX_VENDOR_ID",
   DEFAULT_MEX_PRODUCT_ID : "DEFAULT_MEX_PRODUCT_ID",
   DESCRIPTION : "DESCRIPTION"
}

var  MexAlgPropCol = 
{
   MEX_ALG_ID : "MEX_ALG_ID",
   BTY : "BTY",
   PRINT_TYPE : "PRINT_TYPE",
   DEFAULT_MNT_FMT_ID : "DEFAULT_MNT_FMT_ID",
   SUPPORT_MNT_FMT_IDS : "SUPPORT_MNT_FMT_IDS",
   DESCRIPTION : "DESCRIPTION"
}

var  MntFormatPropCol = 
{
   MNT_FORMAT_ID : "MNT_FORMAT_ID",
   BTY : "BTY",
   PRINT_TYPE : "PRINT_TYPE",
   DEFAULT_MNT_SIZE : "DEFAULT_MNT_SIZE",
   MIN_MNT_SIZE : "MIN_MNT_SIZE",
   MAX_MNT_SIZE : "MAX_MNT_SIZE",
   DESCRIPTION : "DESCRIPTION"
}

var  MntLeveledPropCol = 
{
   MNT_FORMAT_ID : "MNT_FORMAT_ID",
   BTY : "BTY",
   PRINT_TYPE : "PRINT_TYPE",
   LEVEL_ID : "LEVEL_ID",
   AVE_MNT_SIZE : "AVE_MNT_SIZE",
   DESCRIPTION : "DESCRIPTION"
}

var  ObjectLoggerCfgCol = 
{
   ID : "ID",
   EVENT_OBJ_ID : "EVENT_OBJ_ID",
   EVENT_TYPE : "EVENT_TYPE",
   IS_DISABLED : "IS_DISABLED",
   LOG_FILTER : "LOG_FILTER",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

var  SearchAlgPropCol = 
{
   SEARCH_ALG_ID : "SEARCH_ALG_ID",
   BTY_FLAG : "BTY_FLAG",
   QRY_TYPE : "QRY_TYPE",
   DEFAULT_MNT_FMT_ID : "DEFAULT_MNT_FMT_ID",
   SUPPORTED_MNT_FMT_ID : "SUPPORTED_MNT_FMT_ID",
   DESCRIPTION : "DESCRIPTION"
}

var  TxtSearchTemplateCol = 
{
   ID : "ID",
   NAME : "NAME",
   URID : "URID",
   TABLE_NAME : "TABLE_NAME",
   TEMPLATE : "TEMPLATE",
   DESCRIPTION : "DESCRIPTION",
   CREATETIME : "CREATE_TIME",
   CREATEUSER : "CREATE_USER",
   UPDATETIME : "UPDATE_TIME",
   UPDATEUSER : "UPDATE_USER"
}

var  UserPrefCfgCol = 
{
   ID : "ID",
   USER_ID : "USER_ID",
   USER_TYPE : "USER_TYPE",
   MODULE_ID : "MODULE_ID",
   CFG_TYPE : "CFG_TYPE",
   CFG_ID : "CFG_ID",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

var  UserPrefDefCol = 
{
   ID : "ID",
   TYPE : "TYPE",
   NAME : "NAME",
   DESCRIPTION : "DESCRIPTION",
   CONTENT : "CONTENT",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

var  UserWorkLogCfgCol = 
{

   ID : "ID",
   URID : "URID",
   WORK_TYPE : "WORK_TYPE",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
	
}

var  HSAbisSysParamCol = 
{
   NAME : "NAME",
   VALUE : "VALUE"
}

var  HSFileEntryCol = 
{
   PATH_ID : "PATH_ID",
   FILE_NAME : "FILE_NAME",
   FILE_CONTENT : "FILE_CONTENT",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

var  HSPathEntryCol = 
{
   ID : "ID",
   PATH_NAME : "PATH_NAME"
}

var  HSUserLoginRestrictionCfgCol = 
{
   ID : "ID",
   NAME : "NAME",
   RESTRIC_CONTENT : "RESTRIC_CONTENT",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

