var PortalColumnCfgCol =
{
	ID			: "ID",
	NAME		: "NAME",
	DESCRIPTION	: "DESCRIPTION",
	CONTENT		: "CONTENT",
	CREATE_USER	: "CREATE_USER",
	CREATE_TIME	: "CREATE_TIME",
	UPDATE_USER	: "UPDATE_USER",
	UPDATE_TIME	: "UPDATE_TIME"
}
