

var  DefinedQryCfgCol = 
{
   ID : "ID",
   NAME : "NAME",
   QRY_TYPE : "QRY_TYPE",
   BTY_MASK : "BTY_MASK",
   RMT_FLAG : "RMT_FLAG",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   IS_PRIVATE_USE : "IS_PRIVATE_USE",
   QRY_COND : "QRY_COND",
   CATEGORY : "CATEGORY"

}

var  QryCandCol = 
{
   ID : "ID",
   QRY_ID : "QRY_ID",
   CAND_RANK : "CAND_RANK",
   LOC_CARD_ID : "LOC_CARD_ID",
   LOC_CARD_NUM : "LOC_CARD_NUM",
   SCORE : "SCORE",
   UPDATE_TIME : "UPDATE_TIME",
   VERIFY_RESULT : "VERIFY_RESULT",
   SRC_INDEX : "SRC_INDEX",
   BTY : "BTY",
   FGP : "FGP",
   SRC_VID : "SRC_VID",
   SRC_CID : "SRC_CID",
   SRC_GID : "SRC_GID",
   DEST_VID : "DEST_VID",
   DEST_CID : "DEST_CID",
   DEST_GID : "DEST_GID",
   STATUS : "STATUS",
   FLAG_1 : "FLAG_1",
   FLAG_2 : "FLAG_2",
   MATCH_METHOD_ID : "MATCH_METHOD_ID",//比对方法。
   DEST_PID : "DEST_PID"//比对方法。
}

var  QryCandMergeTaskCol = 
{
   ID : "ID",
   DEST_PID_MASK : "DEST_PID_MASK",
   SUBMIT_TIME : "SUBMIT_TIME",
   PRIORITY : "PRIORITY",
   QRY_TYPE : "QRY_TYPE",
   STATUS : "STATUS",
   UPDATE_TIME : "UPDATE_TIME",
   SEARCH_PARAM : "SEARCH_PARAM",
   MATCH_METHOD_ID : "MATCH_METHOD_ID",
   MERGE_PARAM : "MERGE_PARAM"
}

var  QryCandRmtInfoCol = 
{
   QRY_CAND_ID : "QRY_CAND_ID",
   SVR_UNIT_CODE : "SVR_UNIT_CODE",
   SVR_DBID : "SVR_DBID",
   SVR_CARD_ID : "SVR_CARD_ID",
   SVR_CARD_NUM : "SVR_CARD_NUM"
}

var  QryMatchInfoCol = 
{
   ID : "ID",
   QRY_ID : "QRY_ID",
   SEARCH_START_TIME : "SEARCH_START_TIME",
   SEARCH_FINISH_TIME : "SEARCH_FINISH_TIME",
   SEARCH_UNIT_CODE : "SEARCH_UNIT_CODE",
   SEARCH_SYS_ID : "SEARCH_SYS_ID",
   REC_SEARCHED : "REC_SEARCHED",
   ITEM_SEARCHED : "ITEM_SEARCHED"
}

var  QryRmtServerCol = 
{
   QRY_ID : "QRY_ID",
   PURPOSE : "PURPOSE",
   SVR_UNIT_CODE : "SVR_UNIT_CODE",
   RMT_UNIT_CODE : "RMT_UNIT_CODE",
   PXY_UNIT_CODE : "PXY_UNIT_CODE",
   SVR_QRY_ID : "SVR_QRY_ID",
   SVR_EXT_QRY_ID : "SVR_EXT_QRY_ID",
   STATUS : "STATUS",
   DOWNLOAD_FLAG : "DOWNLOAD_FLAG",
   SERCH_PARAM : "SERCH_PARAM",
   EXTRA_INFO : "EXTRA_INFO",
   LAST_ERROR : "LAST_ERROR",
   LAST_OP_TIME : "LAST_OP_TIME",
   ERROR_TIMES : "ERROR_TIMES",
   SYNC_TASK_FLAG : "SYNC_TASK_FLAG",
   SYNC_STATE : "SYNC_STATE",
   EVENT_FLAG : "EVENT_FLAG"
}

var  QrySearchFilterCol = 
{
   ID : "ID",
   MATCH_METHOD_ID : "MATCH_METHOD_ID",
   EXPECT_CAND_COUNT : "EXPECT_CAND_COUNT",
   TEXT_SEARCH_FILTER : "TEXT_SEARCH_FILTER",
   TP_TEN_STRING : "TP_TEN_STRING",
   SEARCH_PARAM : "SEARCH_PARAM",
   SUBMITTED_CANDS : "SUBMITTED_CANDS"
}

var  QrySearchingStatusCol = 
{
   ID : "ID",
   STATUS : "STATUS",
   UPDATE_TIME : "UPDATE_TIME",
   MAIN_MATCH_METHOD_ID : "MAIN_MATCH_METHOD_ID",
   IS_COMPOSITE_TASK : "IS_COMPOSITE_TASK"
}

var  QrySearchSubTaskCandCol = 
{
   QRY_ID : "QRY_ID",
   DEST_PID : "DEST_PID",
   CAND_RANK : "CAND_RANK",
   MATCH_METHOD_ID : "MATCH_METHOD_ID",
   DEST_PID_MASK : "DEST_PID_MASK",
   LOC_CARD_ID : "LOC_CARD_ID",
   SCORE : "SCORE",
   SRC_INDEX : "SRC_INDEX",
   BTY : "BTY",
   FGP : "FGP",
   SRC_VID : "SRC_VID",
   SRC_CID : "SRC_CID",
   SRC_GID : "SRC_GID",
   DEST_VID : "DEST_VID",
   DEST_CID : "DEST_CID",
   DEST_GID : "DEST_GID",
   STATUS : "STATUS",
   FLAG_1 : "FLAG_1",
   FLAG_2 : "FLAG_2"
}

var  QrySearchSubTaskCol = 
{
   ID : "ID",
   DEST_PID_MASK : "DEST_PID_MASK",
   STATUS : "STATUS",
   UPDATE_TIME : "UPDATE_TIME",
   SEARCH_PARAM : "SEARCH_PARAM",
   MATCH_METHOD_ID : "MATCH_METHOD_ID",
   FINISH_TIME : "FINISH_TIME",
   EXPECT_CAND_COUNT : "EXPECT_CAND_COUNT"
//   VIRT_PART_ID : "VIRT_PART_ID"
}

var  QrySrcLPCardCol = 
{
   ID : "ID",
   QRY_ID : "QRY_ID",
   SRC_CARD_ID : "SRC_CARD_ID",
   SRC_CARD_NUM : "SRC_CARD_NUM",
   SRC_INDEX : "SRC_INDEX",
   UPDATE_TIME : "UPDATE_TIME",
   SRC_DATA_MODE : "SRC_DATA_MODE"
}

var  QrySrcLPCardLobCol = 
{
   ID : "ID",
   CARD_ID : "CARD_ID",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_TIME : "UPDATE_TIME",
   BTY : "BTY",
   CID : "CID",
   GID : "GID",
   DATA_TYPE : "DATA_TYPE",
   STORAGE_TYPE : "STORAGE_TYPE"
}

var  QrySrcLPCardLobDBItemCol = 
{
   ID : "ID",
   ITEM_INDEX : "ITEM_INDEX",
   UPDATE_TIME : "UPDATE_TIME",
   DATA_FMT : "DATA_FMT",
   DATA_CRC : "DATA_CRC",
   DATA : "DATA"
}

var  QrySrcTPCardCol = 
{
   ID : "ID",
   QRY_ID : "QRY_ID",
   SRC_CARD_ID : "SRC_CARD_ID",
   SRC_CARD_NUM : "SRC_CARD_NUM",
   SRC_INDEX : "SRC_INDEX",
   UPDATE_TIME : "UPDATE_TIME",
   SRC_DATA_MODE : "SRC_DATA_MODE"
}

var  QrySrcTPCardLobCol = 
{
   ID : "ID",
   CARD_ID : "CARD_ID",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_TIME : "UPDATE_TIME",
   BTY : "BTY",
   FGP : "FGP",
   CID : "CID",
   VID : "VID",
   GID : "GID",
   DATA_TYPE : "DATA_TYPE",
   STORAGE_TYPE : "STORAGE_TYPE"
}

var  QrySrcTPCardLobDBItemCol = 
{
   ID : "ID",
   ITEM_INDEX : "ITEM_INDEX",
   UPDATE_TIME : "UPDATE_TIME",
   DATA_FMT : "DATA_FMT",
   DATA_CRC : "DATA_CRC",
   DATA : "DATA"
}

var  QryTaskCol = 
{
   ID : "ID",
   DBID_MASK : "DBID_MASK",
   QRY_NUM : "QRY_NUM",
   QRY_TASK_UUID : "QRY_TASK_UUID",
   QRY_STATUS : "QRY_STATUS",
   MATCH_PRIORITY : "MATCH_PRIORITY",
   VERIFY_PRIORITY : "VERIFY_PRIORITY",
   QRY_TYPE : "QRY_TYPE",
   COMMENTS : "COMMENTS",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_UNIT_CODE : "UPDATE_UNIT_CODE",
   CREATE_USER : "CREATE_USER",
   CREATE_TIME : "CREATE_TIME",
   CREATE_UNIT_CODE : "CREATE_UNIT_CODE",
   WFID : "WFID",
   MASK_FLAG_1 : "MASK_FLAG_1",
   MASK_FLAG_2 : "MASK_FLAG_2",
   CUR_CAND_CNT : "CUR_CAND_CNT",
   RMT_FLAG : "RMT_FLAG",
   BTY_MASK : "BTY_MASK",
   LAST_VERIFY_RESULT : "LAST_VERIFY_RESULT",
   TO_NEXT_STEP_SET : "TO_NEXT_STEP_SET",
   SUBMIT_USER : "SUBMIT_USER",
   SUBMIT_UNIT_CODE : "SUBMIT_UNIT_CODE",
   SUBMIT_TIME : "SUBMIT_TIME",
   SUBMIT_COMPUTER_IP : "SUBMIT_COMPUTER_IP",
   SUBMIT_COMPUTER_NAME : "SUBMIT_COMPUTER_NAME",
   FIRST_SRC_CARD_ID : "FIRST_SRC_CARD_ID",
   FIRST_SRC_CARD_NUM : "FIRST_SRC_CARD_NUM",
   DEST_PIDS : "DEST_PIDS",
   HIT_PROBABILITY : "HIT_PROBABILITY",
   MATCH_FINISH_TIME : "MATCH_FINISH_TIME",
   VERIFY_FINISH_TIME : "VERIFY_FINISH_TIME"
}

var  QryUnsearchedTaskCol = 
{
   ID : "ID",
   DEST_PID : "DEST_PID",
   MATCH_METHOD_ID : "MATCH_METHOD_ID",
   SUBMIT_USER : "SUBMIT_USER",
   SUBMIT_UNITCODE : "SUBMIT_UNITCODE",
   SUBMIT_TIME : "SUBMIT_TIME",
   PRIORITY : "PRIORITY",
   QRY_TYPE : "QRY_TYPE",
   DEST_PID_MASK : "DEST_PID_MASK",
   DEST_PART_TYPE : "DEST_PART_TYPE",
   STATUS : "STATUS",
   UPDATE_TIME : "UPDATE_TIME"
}

var  QryVerifyInfoCol = 
{
   QRY_ID : "QRY_ID",
   VERIFY_TYPE : "VERIFY_TYPE",
   VERIFY_USER : "VERIFY_USER",
   VERIFY_UNIT_CODE : "VERIFY_UNIT_CODE",
   VERIFY_TIME : "VERIFY_TIME",
   VERIFY_RESULT : "VERIFY_RESULT",
   ASSIGN_VERIFY_USER : "ASSIGN_VERIFY_USER"
}

var  QryWorkingStatusCol = 
{
   ID : "ID",
   UPDATE_TIME : "UPDATE_TIME",
   WORKING_TYPE : "WORKING_TYPE",
   WORKING_USER : "WORKING_USER",
   WORKING_PROC_ID : "WORKING_PROC_ID"
}

var  RegisteredMatchSvrCol = 
{
   ID : "ID",
   COMPUTER_NAME : "COMPUTER_NAME",
   STARTUP_TIME : "STARTUP_TIME",
   MATCH_SVR_UUID : "MATCH_SVR_UUID",
   INSTANCE_ID : "INSTANCE_ID",
   PROC_ID : "PROC_ID",
   LAST_OP_TIME : "LAST_OP_TIME",
   APP_SVR_STARTUP_TIME : "APP_SVR_STARTUP_TIME",
   APP_SVR_UUID : "APP_SVR_UUID"
}

