
var  RmtAutoTaskCfgCol = 
{
   ID : "ID",
   NAME : "NAME",
   UUID : "UUID",
   IS_DOWNLOAD : "IS_DOWNLOAD",
   IS_DISABLED : "IS_DISABLED",
   PURPOSE : "PURPOSE",
   DO_TASK_UNIT_CODE : "DO_TASK_UNIT_CODE",
   DO_TASK_INTERVAL : "DO_TASK_INTERVAL",
   FIRST_DO_TASK_TIME : "FIRST_DO_TASK_TIME",
   REC_DATA_TYPE : "REC_DATA_TYPE",
   REC_SVR_UNIT_CODE : "REC_SVR_UNIT_CODE",
   REC_LOC_DBID : "REC_LOC_DBID",
   REC_SVR_DBID : "REC_SVR_DBID",
   REC_OP_TIME_B : "REC_OP_TIME_B",
   REC_OP_TIME_E : "REC_OP_TIME_E",
   REC_CREATE_USER_NAME : "REC_CREATE_USER_NAME",
   REC_UPDATE_USER_NAME : "REC_UPDATE_USER_NAME",
   REC_CREATE_UNIT_CODE : "REC_CREATE_UNIT_CODE",
   REC_UPDATE_UNIT_CODE : "REC_UPDATE_UNIT_CODE",
   REC_ALLOW_KEYNUMS : "REC_ALLOW_KEYNUMS",
   REC_FORBID_KEYNUMS : "REC_FORBID_KEYNUMS",
   IS_ALLOW_FIRST : "IS_ALLOW_FIRST",
   FLAG : "FLAG",
   EXTRA_INFO : "EXTRA_INFO",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER"
}

var  RmtRouterCol = 
{
   NAME : "NAME",
   TARGET_UNIT_CODE : "TARGET_UNIT_CODE",
   DIRECT_UNIT_CODE : "DIRECT_UNIT_CODE",
   PRIORITY : "PRIORITY",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER"
}

var  RmtServerCol = 
{
   ID : "ID",
   NAME : "NAME",
   UNIT_CODE : "UNIT_CODE",
   ADDRESS : "ADDRESS",
   PORT : "PORT",
   USERNAME : "USERNAME",
   PASSWORD : "PASSWORD",
   IS_DIRECT_LINK : "IS_DIRECT_LINK",
   IS_DIRECT_SUPERIOR : "IS_DIRECT_SUPERIOR",
   IS_FRONT_SERVER : "IS_FRONT_SERVER",
   EXTRA_INFO : "EXTRA_INFO",
   COMMENTS : "COMMENTS",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   CREATE_UNIT_CODE : "CREATE_UNIT_CODE",     
   UPDATE_TIME      : "UPDATE_TIME",
   UPDATE_USER      : "UPDATE_USER",
   UPDATE_UNIT_CODE : "UPDATE_UNIT_CODE",
   QRY_RMT_ROLE     : "QRY_RMT_ROLE",
   QRY_LOCAL_ROLE   : "QRY_LOCAL_ROLE"
}

var  RmtServerDatabaseCol = 
{
   UNIT_CODE : "UNIT_CODE",
   MAP_DBID : "MAP_DBID",
   REAL_DBID : "REAL_DBID",
   DB_NAME : "DB_NAME",
   DB_TYPE : "DB_TYPE",
   WRITABLE : "WRITABLE",
   READABLE : "READABLE",
   SEARCHABLE : "SEARCHABLE",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER"
}
                           

var  RmtTaskHistoryCol = 
{
   ID : "ID",
   WORK_FLOW_ID : "WORK_FLOW_ID",
   QRY_TASK_ID : "QRY_TASK_ID",
   QRY_CAND_ID : "QRY_CAND_ID",
   KEY_NUM : "KEY_NUM",
   RMT_UNIT_CODE : "RMT_UNIT_CODE",
   SVR_UNIT_CODE : "SVR_UNIT_CODE",
   RMT_DBID : "RMT_DBID",
   SVR_DBID : "SVR_DBID",
   DATA_TYPE : "DATA_TYPE",
   IS_DOWNLOAD : "IS_DOWNLOAD",
   IS_QRY_CAND : "IS_QRY_CAND",
   SOURCE : "SOURCE",
   STATUS : "STATUS",
   LAST_ERROR : "LAST_ERROR",
   FINISH_TIME : "FINISH_TIME",
   EXTRA_INFO : "EXTRA_INFO",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   CREATE_UNIT_CODE : "CREATE_UNIT_CODE"
}

var  RmtTaskOpDetailCol = 
{
   TASK_TYPE : "TASK_TYPE",
   TASK_ID : "TASK_ID",
   LAST_OP_TIME : "LAST_OP_TIME"
}

var  RmtTaskQueueCol = 
{
   ID : "ID",
   SVR_QUE_ID : "SVR_QUE_ID",
   WORK_FLOW_ID : "WORK_FLOW_ID",
   QRY_TASK_ID : "QRY_TASK_ID",
   QRY_CAND_ID : "QRY_CAND_ID",
   KEY_NUM : "KEY_NUM",
   RMT_KEY_ID : "RMT_KEY_ID",
   SVR_KEY_ID : "SVR_KEY_ID",
   RMT_UNIT_CODE : "RMT_UNIT_CODE",
   SVR_UNIT_CODE : "SVR_UNIT_CODE",
   RMT_DBID : "RMT_DBID",
   SVR_DBID : "SVR_DBID",
   DATA_TYPE : "DATA_TYPE",
   IS_DOWNLOAD : "IS_DOWNLOAD",
   IS_QRY_CAND : "IS_QRY_CAND",
   SOURCE : "SOURCE",
   STATUS : "STATUS",
   PRIORITY : "PRIORITY",
   FLAG : "FLAG",
   ERROR_TIMES : "ERROR_TIMES",
   LAST_ERROR : "LAST_ERROR",
   LAST_OP_TIME : "LAST_OP_TIME",
   EXTRA_INFO : "EXTRA_INFO",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   CREATE_UNIT_CODE : "CREATE_UNIT_CODE"
}

var	RmtToRmtDatabase = 
{
		MAP_DBID          : "MAP_DBID",
		REAL_DBID         : "REAL_DBID",
		DB_NAME           : "DB_NAME",
		DB_TYPE           : "DB_TYPE",
		WRITABLE          : "WRITABLE",
		READABLE          : "READABLE",
		SEARCHABLE        : "SEARCHABLE",
		CREATE_TIME       : "CREATE_TIME",
		CREATE_USER       : "CREATE_USER"
}

var	RmtTPCardUploadListCol =
{
		ID              : "ID",
		UNI_PERSON_ID	: "UNI_PERSON_ID",
		PERSON_NUM		: "PERSON_NUM",
		MIS_PERSON_NUM	: "MIS_PERSON_NUM",
		CREATE_TIME		: "CREATE_TIME",
		UPDATE_TIME		: "UPDATE_TIME",
		CREATE_USER		: "CREATE_USER",
		UPDATE_USER		: "UPDATE_USER",
		CREATE_UNIT_CODE	: "CREATE_UNIT_CODE",
		UPDATE_UNIT_CODE	: "UPDATE_UNIT_CODE",
		CARD_NUM		: "CARD_NUM",
		PRINT_DATE		: "PRINT_DATE",
		PRINT_BY		: "PRINT_BY",
		PRINT_UNIT_CODE	: "PRINT_UNIT_CODE",
		PRINT_UNIT_NAME	: "PRINT_UNIT_NAME",
		PRINT_REASON	: "PRINT_REASON",
		NAME			: "NAME",
		NAME_PINYIN		: "NAME_PINYIN",
		SHENFEN_ID		: "SHENFEN_ID",
		SEX_CODE		: "SEX_CODE",
		NATION			: "NATION",
		NATIONALITY		: "NATIONALITY",
		PERSON_CLASS_CODE	: "PERSON_CLASS_CODE",
		UPLOAD_STATUS	: "UPLOAD_STATUS",
		RMT_SVR_ID		: "RMT_SVR_ID",
		UPLOAD_TIME		: "UPLOAD_TIME",
		UPLOAD_TYPE		: "UPLOAD_TYPE",
		RMT_SVR_NAME	: "RMT_SVR_NAME",
		RMT_SVR_UNIT_CODE	: "RMT_SVR_UNIT_CODE"		
}

var	RmtLPCaseUploadListCol =
{
		ID                  : "ID",
		CE_NUM              : "CE_NUM",
		CE_NAME             : "CE_NAME",
		CE_TYPE             : "CE_TYPE",
		CREATE_TIME         : "CREATE_TIME",
		UPDATE_TIME         : "UPDATE_TIME",
		CREATE_USER         : "CREATE_USER",
		UPDATE_USER         : "UPDATE_USER",
		CREATE_UNIT_CODE    : "CREATE_UNIT_CODE",
		UPDATE_UNIT_CODE    : "UPDATE_UNIT_CODE",
		CE_STATUS           : "CE_STATUS",
		UPLOAD_STATUS       : "UPLOAD_STATUS",
		RMT_SVR_ID          : "RMT_SVR_ID",
		UPLOAD_TIME         : "UPLOAD_TIME",
		UPLOAD_TYPE         : "UPLOAD_TYPE",
		RMT_SVR_NAME        : "RMT_SVR_NAME",
		RMT_SVR_UNIT_CODE   : "RMT_SVR_UNIT_CODE"		
}

var	RmtLPCardUploadListCol =
{
		ID                    : "ID",
		BTY                   : "BTY",
		SEQ_NO                : "SEQ_NO",
		CARD_NUM              : "CARD_NUM",
		HAS_TP_MATCH          : "HAS_TP_MATCH",
		CREATE_TIME           : "CREATE_TIME",
		UPDATE_TIME           : "UPDATE_TIME",
		CREATE_USER           : "CREATE_USER",
		UPDATE_USER           : "UPDATE_USER",
		CE_NUM                : "CE_NUM",
		CE_NAME               : "CE_NAME",
		CE_TYPE               : "CE_TYPE",
		CE_STATUS             : "CE_STATUS",
		UPLOAD_STATUS         : "UPLOAD_STATUS",
		RMT_SVR_ID            : "RMT_SVR_ID",
		UPLOAD_TIME           : "UPLOAD_TIME",
		UPLOAD_TYPE           : "UPLOAD_TYPE",
		RMT_SVR_NAME          : "RMT_SVR_NAME",
		RMT_SVR_UNIT_CODE     : "RMT_SVR_UNIT_CODE"
}

var RmtGiEnrollUploadListCol =
{
		ID                       : "ID",
		CREATE_TIME              : "CREATE_TIME",
		CREATE_USER              : "CREATE_USER",
		UPDATE_TIME              : "UPDATE_TIME",
		UPDATE_USER              : "UPDATE_USER",
		REGISTER_DATE            : "REGISTER_DATE",
		REGISTER_USER            : "REGISTER_USER",
		REGISTER_UNIT_CODE       : "REGISTER_UNIT_CODE",
		REGISTER_UNIT_NAME       : "REGISTER_UNIT_NAME",
		REGISTER_USER_NAME       : "REGISTER_USER_NAME",
		REGISTER_POLICE_NO       : "REGISTER_POLICE_NO",
		CE_NUM                   : "CE_NUM",
		CE_NAME                  : "CE_NAME",
		CE_ID                    : "CE_ID",
		PERSON_NAME              : "PERSON_NAME",
		PERSON_SHEN_FEN_ID       : "PERSON_SHEN_FEN_ID",
		PERSON_NUM               : "PERSON_NUM",
		PERSON_REC_ID            : "PERSON_REC_ID",
		UPLOAD_STATUS            : "UPLOAD_STATUS",
		RMT_SVR_ID               : "RMT_SVR_ID",
		UPLOAD_TIME              : "UPLOAD_TIME",
		UPLOAD_TYPE              : "UPLOAD_TYPE",
		RMT_SVR_NAME             : "RMT_SVR_NAME",
		RMT_SVR_UNIT_CODE        : "RMT_SVR_UNIT_CODE"
}
