
var  PerfEvalDayDataCol = 
{
   UNIT_CODE : "UNIT_CODE",
   STAT_DATE : "STAT_DATE",
   STAT_TIME : "STAT_TIME",
   CRETAE_TIME : "CRETAE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   TP_TOTAL_LIVE_ENROLL : "TP_TOTAL_LIVE_ENROLL",
   TP_TOTAL_ENROLL : "TP_TOTAL_ENROLL",
   CASE_BREAK_C_LEVEL_LOCAL : "CASE_BREAK_C_LEVEL_LOCAL",
   CASE_BREAK_C_LEVEL_OTHER : "CASE_BREAK_C_LEVEL_OTHER",
   CASE_BREAK_B_LEVEL_LOCAL : "CASE_BREAK_B_LEVEL_LOCAL",
   CASE_BREAK_B_LEVEL_OTHER : "CASE_BREAK_B_LEVEL_OTHER",
   CASE_BREAK_BP_LEVEL_LOCAL : "CASE_BREAK_BP_LEVEL_LOCAL",
   CASE_BREAK_BP_LEVEL_OTHER : "CASE_BREAK_BP_LEVEL_OTHER",
   CASE_BREAK_A_LEVEL_LOCAL : "CASE_BREAK_A_LEVEL_LOCAL",
   CASE_BREAK_A_LEVEL_OTHER : "CASE_BREAK_A_LEVEL_OTHER",
   SUSPECT_HIT_BY_LIVE_SCAN : "SUSPECT_HIT_BY_LIVE_SCAN",
   CASE_HIT_BY_LIVE_SCAN : "CASE_HIT_BY_LIVE_SCAN",
   TL_DELAYED_CHK_FOR_LIVE_SCAN : "TL_DELAYED_CHK_FOR_LIVE_SCAN",
   TOTAL_IMPORTANT_CASE : "TOTAL_IMPORTANT_CASE",
   IMPORTANT_CASE_COLLECTED : "IMPORTANT_CASE_COLLECTED",
   LP_FINGER_ENROLLED : "LP_FINGER_ENROLLED",
   BAD_QUALITY_LP_FINGER : "BAD_QUALITY_LP_FINGER",
   LP_PALM_ENROLLED : "LP_PALM_ENROLLED",
   BAD_QUALITY_LP_PALM : "BAD_QUALITY_LP_PALM",
   CASE_NOT_CLEARED_IN_TIME : "CASE_NOT_CLEARED_IN_TIME",
   CASE_MISS_OR_ERROR : "CASE_MISS_OR_ERROR",
   SUSPECT_HIT_TOTAL : "SUSPECT_HIT_TOTAL",
   SUSPECT_WANTED_TOTAL : "SUSPECT_WANTED_TOTAL",
   SUSPECT_CAPTURED_TOTAL : "SUSPECT_CAPTURED_TOTAL"
}

var  PerfEvalMonthDataCol = 
{
   UNIT_CODE : "UNIT_CODE",
   STAT_DATE : "STAT_DATE",
   NAME : "NAME",
   START_DATE : "START_DATE",
   END_DATE : "END_DATE",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   TP_TOTAL_LIVE_ENROLL : "TP_TOTAL_LIVE_ENROLL",
   TP_EXPECT_LIVE_ENROLL : "TP_EXPECT_LIVE_ENROLL",
   TP_TOTAL_ENROLL : "TP_TOTAL_ENROLL",
   TP_EXPECT_ENROLL : "TP_EXPECT_ENROLL",
   CASE_BREAK_C_LEVEL_LOCAL : "CASE_BREAK_C_LEVEL_LOCAL",
   CASE_BREAK_C_LEVEL_OTHER : "CASE_BREAK_C_LEVEL_OTHER",
   CASE_BREAK_B_LEVEL_LOCAL : "CASE_BREAK_B_LEVEL_LOCAL",
   CASE_BREAK_B_LEVEL_OTHER : "CASE_BREAK_B_LEVEL_OTHER",
   CASE_BREAK_BP_LEVEL_LOCAL : "CASE_BREAK_BP_LEVEL_LOCAL",
   CASE_BREAK_BP_LEVEL_OTHER : "CASE_BREAK_BP_LEVEL_OTHER",
   CASE_BREAK_A_LEVEL_LOCAL : "CASE_BREAK_A_LEVEL_LOCAL",
   CASE_BREAK_A_LEVEL_OTHER : "CASE_BREAK_A_LEVEL_OTHER",
   SUSPECT_HIT_BY_LIVE_SCAN : "SUSPECT_HIT_BY_LIVE_SCAN",
   CASE_HIT_BY_LIVE_SCAN : "CASE_HIT_BY_LIVE_SCAN",
   TL_DELAYED_CHK_FOR_LIVE_SCAN : "TL_DELAYED_CHK_FOR_LIVE_SCAN",
   TOTAL_IMPORTANT_CASE : "TOTAL_IMPORTANT_CASE",
   IMPORTANT_CASE_COLLECTED : "IMPORTANT_CASE_COLLECTED",
   LP_FINGER_ENROLLED : "LP_FINGER_ENROLLED",
   BAD_QUALITY_LP_FINGER : "BAD_QUALITY_LP_FINGER",
   LP_PALM_ENROLLED : "LP_PALM_ENROLLED",
   BAD_QUALITY_LP_PALM : "BAD_QUALITY_LP_PALM",
   CASE_NOT_CLEARED_IN_TIME : "CASE_NOT_CLEARED_IN_TIME",
   CASE_MISS_OR_ERROR : "CASE_MISS_OR_ERROR",
   SUSPECT_HIT_TOTAL : "SUSPECT_HIT_TOTAL",
   SUSPECT_WANTED_TOTAL : "SUSPECT_WANTED_TOTAL",
   SUSPECT_CAPTURED_TOTAL : "SUSPECT_CAPTURED_TOTAL"
}

var  StatAllCountCol = 
{
   STAT_DATE : "STAT_DATE",
   STAT_TIME : "STAT_TIME",
   TP_CARD_COUNT : "TP_CARD_COUNT",
   TP_DUP_CARD_COUNT : "TP_DUP_CARD_COUNT",
   TP_DUP_CARD_GRP_COUNT : "TP_DUP_CARD_GRP_COUNT",
   LP_CASE_COUNT : "LP_CASE_COUNT",
   LP_CARD_COUNT : "LP_CARD_COUNT",
   LTL_HITLOG_COUNT : "LTL_HITLOG_COUNT",
   TT_HITLOG_COUNT : "TT_HITLOG_COUNT",
   LL_HITLOG_COUNT : "LL_HITLOG_COUNT",
   WANTED_PERSON_COUNT : "WANTED_PERSON_COUNT",
   QRY_COUNT : "QRY_COUNT",
   CAPTURED_PERSON_COUNT : "CAPTURED_PERSON_COUNT",
   TABLE_OP_LOG_COUNT : "TABLE_OP_LOG_COUNT",
   TABLE_OP_SELECT_COUNT : "TABLE_OP_SELECT_COUNT",
   TP_EDIT_TASK_COUNT : "TP_EDIT_TASK_COUNT",
   LP_EDIT_TASK_COUNT : "LP_EDIT_TASK_COUNT",
   MEX_TASK_COUNT : "MEX_TASK_COUNT",
   USER_COUNT : "USER_COUNT",
   TP_LOB_IMG_COUNT : "TP_LOB_IMG_COUNT",
   TP_LOB_MNT_COUNT : "TP_LOB_MNT_COUNT",
   GOODS_ITEM_COUNT : "GOODS_ITEM_COUNT",
   NOTICE_COUNT : "NOTICE_COUNT",
   TP_QUAL_CHECK_TASK_COUNT : "TP_QUAL_CHECK_TASK_COUNT",
   LP_QUAL_CHECK_TASK_COUNT : "LP_QUAL_CHECK_TASK_COUNT",
   UNI_PERSON_COUNT : "UNI_PERSON_COUNT",
   TEXT_INPUT_TASK_COUNT : "TEXT_INPUT_TASK_COUNT"
}

var  StatDoStatLogCol = 
{
   ID : "ID",
   STAT_NAME : "STAT_NAME",
   STAT_TIME : "STAT_TIME",
   STAT_TIME_USED : "STAT_TIME_USED",
   STAT_DATE : "STAT_DATE",
   STAT_DATE_TYPE : "STAT_DATE_TYPE"
}

var  StatDoStatTimeCol = 
{
   STAT_NAME : "STAT_NAME",
   LAST_STAT_TIME : "LAST_STAT_TIME",
   STAT_TIME_USED : "STAT_TIME_USED",
   STAT_DATE : "STAT_DATE",
   STAT_DATE_TYPE : "STAT_DATE_TYPE"
}

var  StatLPCardCountCol = 
{
   DBID_MASK : "DBID_MASK",
   STAT_DATE : "STAT_DATE",
   LA_UNIT_CODE : "LA_UNIT_CODE",
   BTY : "BTY",
   HAS_TP_MATCH : "HAS_TP_MATCH",
   SUPERVISE_LEVEL : "SUPERVISE_LEVEL",
   CARD_COUNT : "CARD_COUNT",
   STAT_TIME : "STAT_TIME"
}

var  StatLPCaseCountCol = 
{
   DBID_MASK : "DBID_MASK",
   STAT_DATE : "STAT_DATE",
   LA_UNIT_CODE : "LA_UNIT_CODE",
   HAS_TP_MATCH : "HAS_TP_MATCH",
   CE_STATUS : "CE_STATUS",
   SUPERVISE_LEVEL : "SUPERVISE_LEVEL",
   CE_COUNT : "CE_COUNT",
   STAT_TIME : "STAT_TIME"
}

var  StatOnStorageCol = 
{
   STAT_DATE : "STAT_DATE",
   STAT_TIME : "STAT_TIME",
   DISK_TOTAL_STORAGE_IN_MB : "DISK_TOTAL_STORAGE_IN_MB",
   DISK_FREE_STORAGE_IN_MB : "DISK_FREE_STORAGE_IN_MB",
   DB_FILE_STORAGE_IN_MB : "DB_FILE_STORAGE_IN_MB",
   DB_FILE_FREE_IN_MB : "DB_FILE_FREE_IN_MB"
}

var  StatQryCountCol = 
{
   DBID_MASK : "DBID_MASK",
   STAT_DATE : "STAT_DATE",
   QRY_TYPE : "QRY_TYPE",
   QRY_STATUS : "QRY_STATUS",
   BTY_MASK : "BTY_MASK",
   RMT_FLAG : "RMT_FLAG",
   QRY_COUNT : "QRY_COUNT",
   STAT_TIME : "STAT_TIME"
}

var  StatTPCardCountCol = 
{
   DBID_MASK : "DBID_MASK",
   STAT_DATE : "STAT_DATE",
   STAT_UNIT_CODE : "STAT_UNIT_CODE",
   BTY_MASK : "BTY_MASK",
   ENROLL_TYPE : "ENROLL_TYPE",
   CARD_COUNT : "CARD_COUNT",
   STAT_TIME : "STAT_TIME"
}

var  UnitTaskIndexCol = 
{
   UNIT_CODE : "UNIT_CODE",
   INDEX_TYPE : "INDEX_TYPE",
   INDEX_COUNT : "INDEX_COUNT"
}

var  UserTaskIndexCol = 
{
   USER_ID : "USER_ID",
   INDEX_TYPE : "INDEX_TYPE",
   INDEX_COUNT : "INDEX_COUNT"
}

