
var  MisPersonAddrInfoCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   ADDRESS_TYPE : "ADDRESS_TYPE",
   ADDRESS_CODE : "ADDRESS_CODE",
   ADDRESS_DETAIL : "ADDRESS_DETAIL",
   ADDRESS_ZIP_CODE : "ADDRESS_ZIP_CODE"
}

var  MisPersonBasicInfoCol = 
{
   ID : "ID",
   NAME : "NAME",
   NAME_PINYIN : "NAME_PINYIN",
   BIRTH_DATE : "BIRTH_DATE",
   SEX_CODE : "SEX_CODE",
   NATION : "NATION",
   SHENFEN_ID : "SHENFEN_ID",
   MIN_ZU : "MIN_ZU",
   ALIAS : "ALIAS",
   POLITICAL_AFFILIATION : "POLITICAL_AFFILIATION",
   RELIGIOUS_FAITH : "RELIGIOUS_FAITH",
   MARITAL_STATUS : "MARITAL_STATUS",
   HIGHEST_EDU_DEGREE : "HIGHEST_EDU_DEGREE",
   MILITARY_SERVICE_STATUS : "MILITARY_SERVICE_STATUS",
   COMMENTS : "COMMENTS"
}

var  MisPersonBodyInfoCol = 
{
   ID : "ID",
   BODY_HEIGHT : "BODY_HEIGHT",
   FOOT_LENGTH : "FOOT_LENGTH",
   BODY_WEIGHT : "BODY_WEIGHT",
   BLOOD_TYPE : "BLOOD_TYPE",
   BODY_FEATURE : "BODY_FEATURE",
   HAIR_COLOR : "HAIR_COLOR",
   EYE_COLOR : "EYE_COLOR",
   AUDITION_CAP : "AUDITION_CAP",
   VOCAL_CAP : "VOCAL_CAP",
   ACCENT : "ACCENT",
   FINGER_MISSED_CNT : "FINGER_MISSED_CNT"
}

var  MisPersonCEInfoCol = 
{
   ID : "ID",
   CASE_CLASS_CODE_1 : "CASE_CLASS_CODE_1",
   CASE_CLASS_CODE_2 : "CASE_CLASS_CODE_2",
   CASE_CLASS_CODE_3 : "CASE_CLASS_CODE_3",
   IS_CRIMINAL : "IS_CRIMINAL",
   PERSON_CLASS_CODE : "PERSON_CLASS_CODE",
   CRIMINAL_RECORD : "CRIMINAL_RECORD",
   CASE_NUM : "CASE_NUM"
}

var  MisPersonCertInfoCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   CERT_TYPE : "CERT_TYPE",
   CERT_NUM : "CERT_NUM",
   START_DATE : "START_DATE",
   EXPIRE_DATE : "EXPIRE_DATE",
   ISSUE_BY : "ISSUE_BY",
   ISSUE_DATE : "ISSUE_DATE"
}

var  MisPersonCol = 
{
   ID : "ID",
   DBID : "DBID",
   UNI_PERSON_ID : "UNI_PERSON_ID",
   PERSON_NUM : "PERSON_NUM",
   PERSON_UUID : "PERSON_UUID",
   PERSON_CLASS_CODE : "PERSON_CLASS_CODE"

}

var MisPersonEnrollInfoCol = 
{
		   INI_ENROLL_TIME : "INI_ENROLL_TIME",
		   INI_ENROLL_USER : "INI_ENROLL_USER",
		   INI_ENROLL_UNIT_CODE : "INI_ENROLL_UNIT_CODE",
		   INI_ENROLL_TYPE : "INI_ENROLL_TYPE"	
}

var  MisPersonCommInfoCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   COMM_TYPE : "COMM_TYPE",
   COMM_NUM : "COMM_NUM",
   LOGIN_PASS : "LOGIN_PASS"
}

var  MisPersonDBCol = 
{
   DBID : "DBID",
   MIS_PERSON_ID : "MIS_PERSON_ID",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

var  MisPersonDnaCollectInfoCol = 
{
   ID : "ID",
   DNA_NO : "DNA_NO",
   COLLECT_USER_NAME : "COLLECT_USER_NAME",
   COLLECT_UNIT_CODE : "COLLECT_UNIT_CODE",
   COLLECT_UNIT_NAME : "COLLECT_UNIT_NAME",
   COLLECT_DATE : "COLLECT_DATE",
   CREATE_TIME : "CREATE_TIME"
}

var  MisPersonDnaStorageInfoCol = 
{
   ID : "ID",
   STATE : "STATE",
   QUAL_CHECK_RESULT : "QUAL_CHECK_RESULT",
   UPDATE_TIME : "UPDATE_TIME",
   STORAGE_UNIT_CODE : "STORAGE_UNIT_CODE",
   INBOUND_TIME : "INBOUND_TIME",
   BAD_QUAL_REASON : "BAD_QUAL_REASON",
   LAST_TRANSFER_LOG_ID : "LAST_TRANSFER_LOG_ID"
}

var  MisPersonDnaTransferInfoCol = 
{
   ID : "ID",
   TRANSFER_TYPE : "TRANSFER_TYPE",
   UPDATE_TIME : "UPDATE_TIME",
   OUTBOUND_TIME : "OUTBOUND_TIME",
   OUTBOUND_OP_USER : "OUTBOUND_OP_USER",
   EXPECT_RECEIVE_UNIT_CODE : "EXPECT_RECEIVE_UNIT_CODE",
   RECEIVE_TIME : "RECEIVE_TIME",
   RECEIVE_OP_USER : "RECEIVE_OP_USER",
   CARRIER_NAME : "CARRIER_NAME"
}

var  MisPersonDnaTransferLogCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   DNA_NO : "DNA_NO",
   CREATE_TIME : "CREATE_TIME",
   TRANSFER_TYPE : "TRANSFER_TYPE",
   TRANSFER_RESULT : "TRANSFER_RESULT",
   ORG_STORAGE_UNIT_CODE : "ORG_STORAGE_UNIT_CODE",
   CUR_STORAGE_UNIT_CODE : "CUR_STORAGE_UNIT_CODE",
   OUTBOUND_TIME : "OUTBOUND_TIME",
   OUTBOUND_OP_USER : "OUTBOUND_OP_USER",
   INBOUND_TIME : "INBOUND_TIME",
   INBOUND_OP_USER : "INBOUND_OP_USER",
   CARRIER_NAME : "CARRIER_NAME",
   BAD_QUAL_REASON : "BAD_QUAL_REASON",
   QUAL_CHECK_RESULT : "QUAL_CHECK_RESULT",
   QUAL_CHECK_TIME : "QUAL_CHECK_TIME",
   QUAL_CHECK_USER : "QUAL_CHECK_USER",
   EXPECT_RECEIVE_UNIT_CODE : "EXPECT_RECEIVE_UNIT_CODE"
}

var  MisPersonEduInfoCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   START_DATE : "START_DATE",
   END_DATE : "END_DATE",
   UNIT_NAME : "UNIT_NAME",
   UNIT_ADDRESS : "UNIT_ADDRESS",
   EDU_TYPE : "EDU_TYPE",
   CONTACT_PERSON_NAME : "CONTACT_PERSON_NAME",
   CONTACT_PHONE : "CONTACT_PHONE"
}

var  MisPersonEmploymentInfoCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   START_DATE : "START_DATE",
   END_DATE : "END_DATE",
   UNIT_NAME : "UNIT_NAME",
   UNIT_ADDRESS : "UNIT_ADDRESS",
   CONTACT_PERSON_NAME : "CONTACT_PERSON_NAME",
   CONTACT_PHONE : "CONTACT_PHONE"
}

var  MisPersonEnrollFeedBackCol = 
{
   ID : "ID",
   CARD_ID : "CARD_ID",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_TIME : "UPDATE_TIME",
   FINGER_TT_MATCH_ID : "FINGER_TT_MATCH_ID",
   FINGER_TT_STATUS : "FINGER_TT_STATUS",
   FINGER_TL_MATCH_ID : "FINGER_TL_MATCH_ID",
   FINGER_TL_STATUS : "FINGER_TL_STATUS",
   PALM_TT_MATCH_ID : "PALM_TT_MATCH_ID",
   PALM_TT_STATUS : "PALM_TT_STATUS",
   PALM_TL_MATCH_ID : "PALM_TL_MATCH_ID",
   PALM_TL_STATUS : "PALM_TL_STATUS",
   FACE_TT_MATCH_ID : "FACE_TT_MATCH_ID",
   FACE_TT_STATUS : "FACE_TT_STATUS",
   FACE_TL_MATCH_ID : "FACE_TL_MATCH_ID",
   FACE_TL_STATUS : "FACE_TL_STATUS",
   QUAL_CHECK_ID : "QUAL_CHECK_ID",
   QUAL_CHECK_STATUS : "QUAL_CHECK_STATUS",
   IS_LIVE_SCAN : "IS_LIVE_SCAN"
}

var  MisPersonPhoneInfoCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   PHONE_NUM_TYPE : "PHONE_NUM_TYPE",
   PHONE_NUM : "PHONE_NUM"
}

var  TPCardInfoCol = 
{
   ID : "ID",
   CARD_NUM : "CARD_NUM",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   PRINT_DATE : "PRINT_DATE",
   PRINT_BY : "PRINT_BY",
   PRINT_UNIT_CODE : "PRINT_UNIT_CODE",
   PRINT_UNIT_NAME : "PRINT_UNIT_NAME"
}

var  TPLobsCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_TIME : "UPDATE_TIME",
   BTY : "BTY",
   FGP : "FGP",
   VID : "VID",
   CID : "CID",
   DATA_TYPE : "DATA_TYPE",
   GID : "GID",
   STORAGE_TYPE : "STORAGE_TYPE"
}

var  TPLobsDBItemCol = 
{
   ID : "ID",
   ITEM_INDEX : "ITEM_INDEX",
   UPDATE_TIME : "UPDATE_TIME",
   DATA_FMT : "DATA_FMT",
   DATA_CRC : "DATA_CRC",
   DATA : "DATA"
}

var  UniPersonCol = 
{
   ID : "ID"
}

