
var  QuotaCfgCol = 
{
   ID : "ID",
   NAME : "NAME",
   CFG_TYPE : "CFG_TYPE",
   OP_TYPE : "OP_TYPE",
   CFG_CONTENT : "CFG_CONTENT",
   DESCRIPTION : "DESCRIPTION",
   CREATE_USER : "CREATE_USER",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_TIME : "UPDATE_TIME"
}

var  QuotaUsageForLocQrySubmitCol = 
{
   URID : "URID",
   BTY_MASK : "BTY_MASK",
   QRY_TYPE : "QRY_TYPE",
   QRY_PRIORITY : "QRY_PRIORITY",
   QUOTA_DATE : "QUOTA_DATE",
   USAGE_CNT : "USAGE_CNT"
}

var  QuotaUsageForLPOpCol = 
{
   URID : "URID",
   OP_TYPE : "OP_TYPE",
   QUOTA_DATE : "QUOTA_DATE",
   USAGE_CNT : "USAGE_CNT"
}

var  QuotaUsageForQryOpCol = 
{
   URID : "URID",
   OP_TYPE : "OP_TYPE",
   QUOTA_DATE : "QUOTA_DATE",
   USAGE_CNT : "USAGE_CNT"
}

var  QuotaUsageForRmtQrySubmitCol = 
{
   URID : "URID",
   BTY_MASK : "BTY_MASK",
   QRY_TYPE : "QRY_TYPE",
   QRY_PRIORITY : "QRY_PRIORITY",
   RMT_UNIT_CODE : "RMT_UNIT_CODE",
   QUOTA_DATE : "QUOTA_DATE",
   USAGE_CNT : "USAGE_CNT"
}

var  QuotaUsageForTPOpCol = 
{
   URID : "URID",
   OP_TYPE : "OP_TYPE",
   QUOTA_DATE : "QUOTA_DATE",
   USAGE_CNT : "USAGE_CNT"
}

var  HSDataFilterFilterCol = 
{
   ID : "ID",
   OBJ_TYPE : "OBJ_TYPE",
   OBJ_ID : "OBJ_ID",
   PRIV : "PRIV",
   FILTER_NAME : "FILTER_NAME",
   FILTER_DESCRIPTION : "FILTER_DESCRIPTION",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   ROW_FILTER : "ROW_FILTER",
   COL_FILTER : "COL_FILTER"
}

var  HSDataFilterGroupCol = 
{
   ID : "ID",
   GROUP_NAME : "GROUP_NAME",
   GROUP_DESCRIPTION : "GROUP_DESCRIPTION",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

var  HSDataFilterGroupMemberCol = 
{
   GROUP_ID : "GROUP_ID",
   OBJ_ID : "OBJ_ID",
   PRIV : "PRIV",
   FILTER_ID : "FILTER_ID"
}

var  HSRoleUserLinkCol = 
{
   ROLE_ID : "ROLE_ID",
   USER_ID : "USER_ID"
}

var  HSUnitInfoCol = 
{
   UNIT_CODE : "UNIT_CODE",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER",
   UNIT_TYPE : "UNIT_TYPE",
   NAME : "NAME",
   SHORT_NAME : "SHORT_NAME",
   ADDRESS : "ADDRESS",
   ADDRESS_CODE : "ADDRESS_CODE",
   ZIP_CODE : "ZIP_CODE",
   NATION_CODE : "NATION_CODE",
   CONTACTER_NAME : "CONTACTER_NAME",
   CONTACTER_PHONE : "CONTACTER_PHONE",
   CONTACTER_EMAIL : "CONTACTER_EMAIL"
}

var  HSUnitLevelTreeCol = 
{
   UNIT_CODE : "UNIT_CODE",
   UPPER_LEVEL_UNIT_CODE : "UPPER_LEVEL_UNIT_CODE"
}

var  HSUserDataFilterCol = 
{
   URID : "URID",
   OBJ_ID : "OBJ_ID",
   PRIV : "PRIV",
   FILTER_ID : "FILTER_ID"
}

var  HSUserInfoCol = 
{
   ID : "ID",
   NAME : "NAME",
   SEX_CODE : "SEX_CODE",
   BIRTH_DATE : "BIRTH_DATE",
   LIVING_ADDRESS_CODE : "LIVING_ADDRESS_CODE",
   LIVING_ADDRESS : "LIVING_ADDRESS",
   TITLE : "TITLE",
   MAIN_MOBILE_PHONE_NUM_1 : "MAIN_MOBILE_PHONE_NUM_1",
   MAIN_MOBILE_PHONE_NUM_2 : "MAIN_MOBILE_PHONE_NUM_2",
   MAIN_FIXED_PHONE_NUM_1 : "MAIN_FIXED_PHONE_NUM_1",
   OTHER_MOBILE_PHONE_NUM_1 : "OTHER_MOBILE_PHONE_NUM_1",
   OTHER_MOBILE_PHONE_NUM_2 : "OTHER_MOBILE_PHONE_NUM_2",
   EMAIL_1 : "EMAIL_1",
   EMAIL_2 : "EMAIL_2",
   QQ_1 : "QQ_1",
   WEI_XIN_1 : "WEI_XIN_1",
   COMMENTS : "COMMENTS"
}

var  HSUserLoginsCol = 
{
   ID : "ID",
   PASSWORDS : "PASSWORDS",
   UPDATE_TIME : "UPDATE_TIME"
}

var  HSUserLoginStatusCol = 
{
   ID : "ID",
   LAST_LOGIN_TIME : "LAST_LOGIN_TIME",
   IS_LAST_LOGIN_FAILED : "IS_LAST_LOGIN_FAILED",
   LOCKED_TIME : "LOCKED_TIME",
   IS_LOCKED : "IS_LOCKED",
   LOGIN_FAILED_CNT : "LOGIN_FAILED_CNT"
}

var  HSUserQuotaCfgCol = 
{
   URID : "URID",
   CFG_TYPE : "CFG_TYPE",
   OP_TYPE : "OP_TYPE",
   CFG_ID : "CFG_ID"
}

var  HSUserRolePrivCol = 
{
   ID : "ID",
   OBJ_TYPE : "OBJ_TYPE",
   OBJ_ID : "OBJ_ID",
   URID : "URID",
   PRIV : "PRIV",
   IS_DISABLED : "IS_DISABLED",
   COL_FILTER : "COL_FILTER",
   ROW_FILTER : "ROW_FILTER",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_TIME : "UPDATE_TIME"
}

var  HSUserRolesCol = 
{
   ID : "ID",
   USER_ID : "USER_ID",
   NAME : "NAME",
   DESCRIPTION : "DESCRIPTION",
   TYPE : "TYPE",
   IS_DISABLED : "IS_DISABLED",
   IS_DELETED : "IS_DELETED"
}

var  HSUsersCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   UNIT_CODE : "UNIT_CODE",
   UNIT_ID : "UNIT_ID",
   //IS_REMOTE_USER : "IS_REMOTE_USER",
   USER_LEVEL : "USER_LEVEL"
}

