
var  WantedCaseLinkCol = 
{
   WANTED_ID : "WANTED_ID",
   LP_CASE_ID : "LP_CASE_ID",
   UPDATE_TIME : "UPDATE_TIME",
   IS_WANTED_GENERATED : "IS_WANTED_GENERATED",
   UPDATE_USER : "UPDATE_USER"
}

var  WantedPersonAuditLogCol = 
{
   ID : "ID",
   WANTED_ID : "WANTED_ID",
   TASK_TYPE : "TASK_TYPE",
   AUDIT_USER : "AUDIT_USER",
   AUDIT_UNIT_CODE : "AUDIT_UNIT_CODE",
   AUDIT_DATE : "AUDIT_DATE",
   AUDIT_RESULT : "AUDIT_RESULT",
   AUDIT_COMMENTS : "AUDIT_COMMENTS"
}

var  WantedPersonAuditTaskCol = 
{
   ID : "ID",
   PRIORITY : "PRIORITY",
   STATUS : "STATUS",
   CREATE_TIME : "CREATE_TIME",
   TASK_TYPE : "TASK_TYPE",
   WORKING_TIME : "WORKING_TIME",
   BPM_ID : "BPM_ID"
}

var  WantedPersonCanceledLogCol = 
{
   ID : "ID",
   CANCEL_DATE : "CANCEL_DATE",
   CANCEL_REASON : "CANCEL_REASON",
   CANCEL_FILL_IN_USER : "CANCEL_FILL_IN_USER",
   CANCEL_APPROVED_BY : "CANCEL_APPROVED_BY",
   CAPTURE_ID : "CAPTURE_ID"
}

var  WantedPersonCaseInfoCol = 
{
   ID : "ID",
   CASE_NUM : "CASE_NUM",
   CASE_DESC : "CASE_DESC",
   REGI_UNIT_CODE : "REGI_UNIT_CODE",
   REGI_DATE : "REGI_DATE",
   REGI_UNIT_NAME : "REGI_UNIT_NAME",
   REGI_UNIT_TYPE : "REGI_UNIT_TYPE",
   ZB_UNIT_CODE : "ZB_UNIT_CODE",
   ZB_UNIT_NAME : "ZB_UNIT_NAME",
   CASE_CLASS_CODE : "CASE_CLASS_CODE",
   SUPERVISE_LEVEL : "SUPERVISE_LEVEL",
   CASE_OCCUR_DATE : "CASE_OCCUR_DATE",
   CASE_OCCUR_PLACE_CODE : "CASE_OCCUR_PLACE_CODE",
   CASE_OCCUR_PLACE : "CASE_OCCUR_PLACE",
   CASE_LOSS : "CASE_LOSS",
   CASE_COMMIT_TYPE : "CASE_COMMIT_TYPE"
}

var  WantedPersonColModLogCol = 
{
   ID : "ID",
   WANTED_PERSON_ID : "WANTED_PERSON_ID",
   WANTED_PERSON_NUM : "WANTED_PERSON_NUM",
   COL_NAME : "COL_NAME",
   OLD_VALUE : "OLD_VALUE",
   NEW_VALUE : "NEW_VALUE"
}

var  WantedPersonInfoCol = 
{
   ID : "ID",
   NAME : "NAME",
   ALIAS : "ALIAS",
   BIRTH_DATE : "BIRTH_DATE",
   SEX_CODE : "SEX_CODE",
   NATION : "NATION",
   NATIONALITY : "NATIONALITY",
   SHEN_FEN_ID : "SHEN_FEN_ID",
   CERTIFICATE_TYPE : "CERTIFICATE_TYPE",
   CERTIFICATE_CODE : "CERTIFICATE_CODE",
   HUKOU_PLACE_CODE : "HUKOU_PLACE_CODE",
   HUKOU_PLACE : "HUKOU_PLACE",
   ADDRESS_CODE : "ADDRESS_CODE",
   ADDRESS_DETAIL : "ADDRESS_DETAIL",
   BODY_HEIGHT : "BODY_HEIGHT",
   ACCENT_CODE : "ACCENT_CODE",
   OCCUPATION_CODE : "OCCUPATION_CODE",
   BODY_FEATURE : "BODY_FEATURE",
   SMT : "SMT"
}

var  WantedPersonLinkCol = 
{
   WANTED_ID : "WANTED_ID",
   PERSON_ID : "PERSON_ID",
   UPDATE_TIME : "UPDATE_TIME",
   IS_WANTED_GENERATED : "IS_WANTED_GENERATED",
   UPDATE_USER : "UPDATE_USER"
}

var  WantedPersonMainCol = 
{
   ID : "ID",
   WANTED_TYPE : "WANTED_TYPE",
   WANTED_STATUS : "WANTED_STATUS",
   WANTED_NO : "WANTED_NO",
   WANTED_BY : "WANTED_BY",
   CONTACTER : "CONTACTER",
   CONTACTER_PHONE : "CONTACTER_PHONE",
   CREATE_TIME : "CREATE_TIME",
   CREATE_USER : "CREATE_USER",
   CREATE_UNIT_CODE : "CREATE_UNIT_CODE",
   UPDATE_USER : "UPDATE_USER",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_UNIT_CODE : "UPDATE_UNIT_CODE",
   COMMENTS : "COMMENTS",
   ESCAPE_DATE : "ESCAPE_DATE",
   ESCAPE_DIRECTION : "ESCAPE_DIRECTION",
   ESCAPE_TYPE : "ESCAPE_TYPE",
   AWARD : "AWARD",
   FILL_IN_USER : "FILL_IN_USER",
   FILL_IN_UNIT_CODE : "FILL_IN_UNIT_CODE",
   FILL_IN_TIME : "FILL_IN_TIME",
   FILL_IN_APPROVED_BY : "FILL_IN_APPROVED_BY",
   EXPIRATION_DATE : "EXPIRATION_DATE",
   ZTW_FILL_IN_USER : "ZTW_FILL_IN_USER",
   ZTW_FILL_IN_TIME : "ZTW_FILL_IN_TIME",
   ZTW_FILL_IN_UNIT_CODE : "ZTW_FILL_IN_UNIT_CODE",
   ZTW_FILL_IN_APPROVED_BY : "ZTW_FILL_IN_APPROVED_BY",
   WANTED_LEVEL : "WANTED_LEVEL",
   ARREST_LEVEL : "ARREST_LEVEL"
}

var  WantedPersonOpLogCol = 
{
   ID : "ID",
   PERSON_ID : "PERSON_ID",
   PERSON_NUM : "PERSON_NUM",
   OP_TYPE : "OP_TYPE",
   OP_USER : "OP_USER",
   OP_TIME : "OP_TIME"
}

var  WantedSuspectTPCardCol = 
{
   WANTED_ID : "WANTED_ID",
   TP_CARD_ID : "TP_CARD_ID",
   TP_CARD_GROUP_ID : "TP_CARD_GROUP_ID",
   STATUS : "STATUS"
}

var  WantedTTSuspectCol = 
{
   CAND_ID : "CAND_ID",
   WANTED_ID : "WANTED_ID",
   STATUS : "STATUS",
   CREATE_TIME : "CREATE_TIME",
   UPDATE_TIME : "UPDATE_TIME",
   SHEN_FEN_ID_CMP_RES : "SHEN_FEN_ID_CMP_RES",
   NAME_CMP_RES : "NAME_CMP_RES",
   PRINT_ESCAPE_DATE_CMP_RES : "PRINT_ESCAPE_DATE_CMP_RES",
   COMPOSITE_SCORE : "COMPOSITE_SCORE"
}

var  WantedUniPersonLinkCol = 
{
   WANTED_ID : "WANTED_ID",
   UNI_PERSON_ID : "UNI_PERSON_ID",
   UPDATE_TIME : "UPDATE_TIME",
   UPDATE_USER : "UPDATE_USER"
}

